version: "3.7"
services:
  mongo:
    image: mongo:2.4.14
  api:
    build: .
    links:
      - mongo
    ports:
      - 8080:8080
  blf:
    build:
      context: ./blf
    links:
      - api
    ports:
      - 3000:3000
