#!/usr/bin/python
# -*- coding: utf-8 -*-
# coding=utf-8

iso3166_alpha3_list = [
    "AD",
    "AE",
    "AF",
    "AG",
    "AI",
    "AL",
    "AM",
    "AN",
    "AO",
    "AQ",
    "AR",
    "AS",
    "AT",
    "AU",
    "AW",
    "AX",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BM",
    "BN",
    "BO",
    "BR",
    "BS",
    "BT",
    "BV",
    "BW",
    "BY",
    "BZ",
    "CA",
    "CC",
    "CD",
    "CF",
    "CG",
    "CH",
    "CI",
    "CK",
    "CL",
    "CM",
    "CN",
    "CO",
    "CR",
    "CU",
    "CV",
    "CX",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "EH",
    "ER",
    "ES",
    "ET",
    "FI",
    "FJ",
    "FK",
    "FM",
    "FO",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GF",
    "GG",
    "GH",
    "GI",
    "GL",
    "GM",
    "GN",
    "GP",
    "GQ",
    "GR",
    "GS",
    "GT",
    "GU",
    "GW",
    "GY",
    "HK",
    "HM",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IM",
    "IN",
    "IO",
    "IQ",
    "IR",
    "IS",
    "IT",
    "JE",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KP",
    "KR",
    "KW",
    "KY",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MG",
    "MH",
    "MK",
    "ML",
    "MM",
    "MN",
    "MO",
    "MP",
    "MQ",
    "MR",
    "MS",
    "MT",
    "MU",
    "MV",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NC",
    "NE",
    "NF",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NU",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PF",
    "PG",
    "PH",
    "PK",
    "PL",
    "PM",
    "PN",
    "PR",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RE",
    "RO",
    "RS",
    "RU",
    "RW",
    "SA",
    "SB",
    "SC",
    "SD",
    "SE",
    "SG",
    "SH",
    "SI",
    "SJ",
    "SK",
    "SL",
    "SM",
    "SN",
    "SO",
    "SR",
    "ST",
    "SV",
    "SY",
    "SZ",
    "TC",
    "TD",
    "TF",
    "TG",
    "TH",
    "TJ",
    "TK",
    "TL",
    "TM",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "UM",
    "US",
    "UY",
    "UZ",
    "VA",
    "VC",
    "VE",
    "VG",
    "VI",
    "VN",
    "VU",
    "WF",
    "WS",
    "YE",
    "YT",
    "ZA",
    "ZM",
    "ZW",
    "ZZ"
]

marccountry_to_iso3166_alpha2 = {
    "aa": "AL",
    "ae": "DZ",
    "af": "AF",
    "ag": "AR",
    "ai": "AM",
    "aj": "AZ",
    "am": "AI",
    "an": "AD",
    "ao": "AO",
    "aq": "AG",
    "as": "AS",
    "at": "AU",
    "au": "AT",
    "aw": "AW",
    "ay": "AQ",
    "ba": "BH",
    "bb": "BB",
    "bd": "BI",
    "be": "BE",
    "bf": "BS",
    "bg": "BD",
    "bh": "BZ",
    "bi": "IO",
    "bl": "BR",
    "bm": "BM",
    "bn": "BA",
    "bo": "BO",
    "bp": "SB",
    "br": "MM",
    "bs": "BW",
    "bt": "BT",
    "bu": "BG",
    "bv": "BV",
    "bw": "BY",
    "bx": "BN",
    "cb": "KH",
    "cd": "TD",
    "ce": "LK",
    "cf": "CG",
    "cg": "CD",
    "ch": "CN",
    "ch": "MO",
    "ch": "TW",
    "ci": "HR",
    "cj": "KY",
    "ck": "CO",
    "cl": "CL",
    "cm": "CM",
    "cq": "KM",
    "cr": "CR",
    "cu": "CU",
    "cv": "CV",
    "cw": "CK",
    "cx": "CF",
    "cy": "CY",
    "dk": "DK",
    "dm": "BJ",
    "dq": "DM",
    "dr": "DO",
    "ea": "ER",
    "ec": "EC",
    "eg": "GQ",
    "em": "TL",
    "enk": "GB",
    "er": "EE",
    "es": "SV",
    "et": "ET",
    "fa": "FO",
    "fg": "GF",
    "fi": "AX",
    "fi": "FI",
    "fj": "FJ",
    "fk": "FK",
    "fm": "FM",
    "fp": "PF",
    "fr": "FR",
    "fs": "TF",
    "ft": "DJ",
    "gb": "KI",
    "gd": "GD",
    "gh": "GH",
    "gi": "GI",
    "gl": "GL",
    "gm": "GM",
    "go": "GA",
    "gp": "GP",
    "gr": "GR",
    "gs": "GE",
    "gt": "GT",
    "gu": "GU",
    "gv": "GN",
    "gw": "DE",
    "gy": "GY",
    "hk": "HK",
    "hm": "HM",
    "ho": "HN",
    "ht": "HT",
    "hu": "HU",
    "ic": "IS",
    "ie": "IE",
    "ii": "IN",
    "io": "ID",
    "iq": "IQ",
    "ir": "IR",
    "is": "IL",
    "it": "IT",
    "iv": "CI",
    "ja": "JP",
    "jm": "JM",
    "jo": "JO",
    "ke": "KE",
    "kg": "KG",
    "kn": "KP",
    "ko": "KR",
    "ku": "KW",
    "kz": "KZ",
    "lb": "LR",
    "le": "LB",
    "lh": "LI",
    "li": "LT",
    "lo": "LS",
    "ls": "LA",
    "lu": "LU",
    "lv": "LV",
    "ly": "LY",
    "mc": "MC",
    "mf": "MU",
    "mg": "MG",
    "mj": "MS",
    "mk": "OM",
    "ml": "ML",
    "mm": "MT",
    "mo": "ME",
    "mp": "MN",
    "mq": "MQ",
    "mr": "MA",
    "mu": "MR",
    "mv": "MD",
    "mw": "MW",
    "mx": "MX",
    "my": "MY",
    "mz": "MZ",
    "na": "AN",
    "ne": "NL",
    "ng": "NE",
    "nl": "NC",
    "nn": "VU",
    "no": "NO",
    "no": "SJ",
    "np": "NP",
    "nq": "NI",
    "nr": "NG",
    "nu": "NR",
    "nw": "MP",
    "nx": "NF",
    "nz": "NZ",
    "ot": "YT",
    "pc": "PN",
    "pe": "PE",
    "pg": "GW",
    "ph": "PH",
    "pk": "PK",
    "pl": "PL",
    "pn": "PA",
    "po": "PT",
    "pp": "PG",
    "pr": "PR",
    "pw": "PW",
    "py": "PY",
    "qa": "QA",
    "rb": "RS",
    "re": "RE",
    "rh": "ZW",
    "rm": "RO",
    "ru": "RU",
    "rw": "RW",
    "sa": "ZA",
    "se": "SC",
    "sf": "ST",
    "sg": "SN",
    "si": "SG",
    "sj": "SD",
    "sl": "SL",
    "sm": "SM",
    "so": "SO",
    "sp": "ES",
    "sq": "SZ",
    "sr": "SR",
    "ss": "EH",
    "su": "SA",
    "sw": "SE",
    "sx": "NA",
    "sy": "SY",
    "sz": "CH",
    "ta": "TJ",
    "tc": "TC",
    "tg": "TG",
    "th": "TH",
    "ti": "TN",
    "tk": "TM",
    "tl": "TK",
    "to": "TO",
    "tr": "TT",
    "ts": "AE",
    "tu": "TR",
    "tv": "TV",
    "tz": "TZ",
    "ua": "EG",
    "ug": "UG",
    "uik": "GG",
    "uik": "IM",
    "uik": "JE",
    "un": "UA",
    "uv": "BF",
    "uy": "UY",
    "uz": "UZ",
    "vb": "VG",
    "vc": "VA",
    "ve": "VE",
    "vi": "VI",
    "vm": "VN",
    "wf": "WF",
    "ws": "WS",
    "xa": "CX",
    "xb": "CC",
    "xc": "MV",
    "xd": "KN",
    "xe": "MH",
    "xh": "NU",
    "xj": "SH",
    "xk": "LC",
    "xl": "PM",
    "xm": "VC",
    "xn": "MK",
    "xo": "SK",
    "xr": "CZ",
    "xs": "GS",
    "xv": "SI",
    "xxc": "CA",
    "xxu": "US",
    "ye": "YE",
    "za": "ZM"
}

english_to_iso3166_alpha2 = {
    "afghanistan": "AF",
    "albania": "AL",
    "algeria": "DZ",
    "åland islands": "AX",
    "american samoa": "AS",
    "andorra": "AD",
    "angola": "AO",
    "anguilla": "AI",
    "antarctica": "AQ",
    "antigua and barbuda": "AG",
    "argentina": "AR",
    "armenia": "AM",
    "aruba": "AW",
    "australia": "AU",
    "austria": "AT",
    "azerbaijan": "AZ",
    "bahamas (the)": "BS",
    "bahrain": "BH",
    "bangladesh": "BD",
    "barbados": "BB",
    "belarus": "BY",
    "belgium": "BE",
    "belize": "BZ",
    "benin": "BJ",
    "bermuda": "BM",
    "bhutan": "BT",
    "bolivia": "BO",
    "bosnia and herzegovina": "BA",
    "botswana": "BW",
    "bouvet island": "BV",
    "brazil": "BR",
    "british indian ocean territory": "IO",
    "brunei darussalam": "BN",
    "bulgaria": "BG",
    "burkina faso": "BF",
    "burundi": "BI",
    "cambodia": "KH",
    "cameroon": "CM",
    "canada": "CA",
    "cape verde": "CV",
    "cayman islands": "KY",
    "central african republic (the)": "CF",
    "chad": "TD",
    "chile": "CL",
    "china": "CN",
    "christmas island": "CX",
    "cocos (keeling) islands": "CC",
    "colombia": "CO",
    "comoros": "KM",
    "congo": "CG",
    "congo, the democratic republic of the": "CD",
    "cook islands": "CK",
    "costa rica": "CR",
    "croatia": "HR",
    "cuba": "CU",
    "cyprus": "CY",
    "czech republic (the)": "CZ",
    "denmark": "DK",
    "djibouti": "DJ",
    "dominica": "DM",
    "dominican republic (the)": "DO",
    "ecuador": "EC",
    "egypt": "EG",
    "el salvador": "SV",
    "equatorial guinea": "GQ",
    "eritrea": "ER",
    "estonia": "EE",
    "ethiopia": "ET",
    "falkland islands (malvinas)": "FK",
    "faroe islands": "FO",
    "fiji": "FJ",
    "finland": "FI",
    "france": "FR",
    "french guiana": "GF",
    "french polynesia": "PF",
    "french southern territories": "TF",
    "gabon": "GA",
    "gambia (the)": "GM",
    "georgia": "GE",
    "germany": "DE",
    "ghana": "GH",
    "gibraltar": "GI",
    "greece": "GR",
    "greenland": "GL",
    "grenada": "GD",
    "guadeloupe": "GP",
    "guam": "GU",
    "guatemala": "GT",
    "guernsey": "GG",
    "guinea": "GN",
    "guinea-bissau": "GW",
    "guyana": "GY",
    "haiti": "HT",
    "heard island and mcdonald islands": "HM",
    "holy see (the)": "VA",
    "honduras": "HN",
    "hong kong": "HK",
    "hungary": "HU",
    "iceland": "IS",
    "india": "IN",
    "indonesia": "ID",
    "iran, islamic republic of": "IR",
    "iraq": "IQ",
    "ireland": "IE",
    "isle of man": "IM",
    "israel": "IL",
    "italy": "IT",
    "ivory coast": "CI",
    "jamaica": "JM",
    "japan": "JP",
    "jersey": "JE",
    "jordan": "JO",
    "kazakhstan": "KZ",
    "kenya": "KE",
    "kiribati": "KI",
    "korea, democratic people's republic of": "KP",
    "korea, republic of": "KR",
    "kuwait": "KW",
    "kyrgyzstan": "KG",
    "lao people's democratic republic": "LA",
    "latvia": "LV",
    "lebanon": "LB",
    "lesotho": "LS",
    "liberia": "LR",
    "libyan arab jamahiriya": "LY",
    "liechtenstein": "LI",
    "lithuania": "LT",
    "luxembourg": "LU",
    "macao": "MO",
    "macedonia, the former yugoslav republic of": "MK",
    "madagascar": "MG",
    "malawi": "MW",
    "malaysia": "MY",
    "maldives": "MV",
    "mali": "ML",
    "malta": "MT",
    "marshall islands (the)": "MH",
    "martinique": "MQ",
    "mauritania": "MR",
    "mauritius": "MU",
    "mayotte": "YT",
    "mexico": "MX",
    "micronesia, federated states of": "FM",
    "moldova, republic of": "MD",
    "monaco": "MC",
    "mongolia": "MN",
    "montenegro": "ME",
    "montserrat": "MS",
    "morocco": "MA",
    "mozambique": "MZ",
    "multiple country": "ZZ",
    "myanmar (burma)": "MM",
    "namibia": "NA",
    "nauru": "NR",
    "nepal": "NP",
    "netherlands (the)": "NL",
    "netherlands antilles": "AN",
    "new caledonia": "NC",
    "new zealand": "NZ",
    "nicaragua": "NI",
    "niger (the)": "NE",
    "nigeria": "NG",
    "niue": "NU",
    "norfolk island": "NF",
    "northern mariana islands": "MP",
    "norway": "NO",
    "oman": "OM",
    "pakistan": "PK",
    "palau": "PW",
    "palestinian territory, occupied": "PS",
    "panama": "PA",
    "papua new guinea": "PG",
    "paraguay": "PY",
    "peru": "PE",
    "philippines (the)": "PH",
    "pitcairn": "PN",
    "poland": "PL",
    "portugal": "PT",
    "puerto rico": "PR",
    "qatar": "QA",
    "romania": "RO",
    "russian federation": "RU",
    "rwanda": "RW",
    "réunion": "RE",
    "saint helena": "SH",
    "saint kitts and nevis": "KN",
    "saint lucia": "LC",
    "saint pierre and miquelon": "PM",
    "saint vincent and the grenadines": "VC",
    "samoa, western": "WS",
    "san marino": "SM",
    "sao tome and principe": "ST",
    "saudi arabia": "SA",
    "senegal": "SN",
    "serbia": "RS",
    "seychelles": "SC",
    "sierra leone": "SL",
    "singapore": "SG",
    "slovakia": "SK",
    "slovenia": "SI",
    "solomon islands": "SB",
    "somalia": "SO",
    "south africa": "ZA",
    "south georgia and the south sandwich islands": "GS",
    "spain": "ES",
    "sri lanka": "LK",
    "sudan": "SD",
    "suriname": "SR",
    "svalbard and jan mayen": "SJ",
    "swaziland": "SZ",
    "sweden": "SE",
    "switzerland": "CH",
    "syrian arab republic": "SY",
    "taiwan, province of china": "TW",
    "tajikistan": "TJ",
    "tanzania, united reprublic of": "TZ",
    "thailand": "TH",
    "timor-leste": "TL",
    "togo": "TG",
    "tokelau": "TK",
    "tonga": "TO",
    "trinidad and tobago": "TT",
    "tunisia": "TN",
    "turkey": "TR",
    "turkmenistan": "TM",
    "turks and caicos islands": "TC",
    "tuvalu": "TV",
    "uganda": "UG",
    "ukraine": "UA",
    "united arab emirates": "AE",
    "united kingdom (the)": "GB",
    "united states (the)": "US",
    "united states minor outlying islands": "UM",
    "uruguay": "UY",
    "uzbekistan": "UZ",
    "vanuatu": "VU",
    "venezuela": "VE",
    "viet nam": "VN",
    "virgin islands, british": "VG",
    "virgin islands, u.s.": "VI",
    "wallis and futuna": "WF",
    "western sahara": "EH",
    "yemen": "YE",
    "zambia": "ZM",
    "zimbabwe": "ZW"
}

french_to_iso3166_alpha2 = {
    "afghanistan": "AF",
    "åland, îles": "AX",
    "albanie": "AL",
    "algérie": "DZ",
    "allemagne": "DE",
    "andorre": "AD",
    "angola": "AO",
    "anguilla": "AI",
    "antarctique": "AQ",
    "antigua et barbuda": "AG",
    "antilles néerlandaises": "AN",
    "arabie saoudite": "SA",
    "argentine": "AR",
    "arménie": "AM",
    "aruba": "AW",
    "australie": "AU",
    "autriche": "AT",
    "azerbaïdjan": "AZ",
    "bahamas": "BS",
    "bahreïn": "BH",
    "bangladesh": "BD",
    "barbade": "BB",
    "bélarus": "BY",
    "belgique": "BE",
    "belize": "BZ",
    "bénin": "BJ",
    "bermudes": "BM",
    "bhoutan": "BT",
    "bolivie": "BO",
    "bosnie-herzégovine": "BA",
    "botswana": "BW",
    "brésil": "BR",
    "brunei": "BN",
    "bulgarie": "BG",
    "burundi": "BI",
    "cambodge": "KH",
    "cameroun": "CM",
    "canada": "CA",
    "cap-vert": "CV",
    "centrafrique": "CF",
    "chili": "CL",
    "chine": "CN",
    "chypre": "CY",
    "colombie": "CO",
    "comores": "KM",
    "congo": "CG",
    "congo-kinshasa": "CD",
    "cook, îles": "CK",
    "corée du nord": "KP",
    "corée du sud": "KR",
    "costa rica": "CR",
    "côte d'ivoire": "CI",
    "croatie": "HR",
    "cuba": "CU",
    "danemark": "DK",
    "djibouti": "DJ",
    "dominicaine, république": "DO",
    "dominique": "DM",
    "equateur": "EC",
    "erythrée": "ER",
    "estonie": "EE",
    "ethiopie": "ET",
    "fidji": "FJ",
    "finlande": "FI",
    "france": "FR",
    "gabon": "GA",
    "gambie": "GM",
    "géorgie": "GE",
    "géorgie du sud et les îles sandwich du sud": "GS",
    "ghana": "GH",
    "gibraltar": "GI",
    "grèce": "GR",
    "grenade": "GD",
    "groenland": "GL",
    "guadeloupe": "GP",
    "guam": "GU",
    "guatemala": "GT",
    "guinée": "GN",
    "guinée equatoriale": "GQ",
    "guinée-bissau": "GW",
    "guyana": "GY",
    "guyane": "GF",
    "haïti": "HT",
    "honduras": "HN",
    "hong kong": "HK",
    "hongrie": "HU",
    "île bouvet": "BV",
    "île christmas": "CX",
    "île heard et îles mcdonald": "HM",
    "îles caïmanes": "KY",
    "îles cocos": "CC",
    "îles féroé": "FO",
    "îles malouines (falkland)": "FK",
    "îles mariannes du nord": "MP",
    "îles mineures éloignées des états-unis": "UM",
    "îles salomon": "SB",
    "îles vierges britanniques": "VG",
    "inde": "IN",
    "indonésie": "ID",
    "iran": "IR",
    "iraq": "IQ",
    "irlande": "IE",
    "islande": "IS",
    "israël": "IL",
    "italie": "IT",
    "jamaïque": "JM",
    "japon": "JP",
    "jordanie": "JO",
    "kazakhstan": "KZ",
    "kenya": "KE",
    "kirghizistan": "KG",
    "kiribati": "KI",
    "koweït": "KW",
    "laos": "LA",
    "lesotho": "LS",
    "lettonie": "LV",
    "liban": "LB",
    "liberia": "LR",
    "libye": "LY",
    "liechtenstein": "LI",
    "lituanie": "LT",
    "luxembourg": "LU",
    "macao": "MO",
    "madagascar": "MG",
    "malaisie": "MY",
    "malawi": "MW",
    "maldives": "MV",
    "mali": "ML",
    "malte": "MT",
    "maroc": "MA",
    "marshall": "MH",
    "martinique": "MQ",
    "maurice": "MU",
    "mauritanie": "MR",
    "mayotte": "YT",
    "mexique": "MX",
    "micronésie": "FM",
    "moldavie, république de": "MD",
    "monaco": "MC",
    "mongolie": "MN",
    "monténégro": "ME",
    "montserrat": "MS",
    "mozambique": "MZ",
    "myanmar (birmanie)": "MM",
    "namibie": "NA",
    "nauru": "NR",
    "népal": "NP",
    "nicaragua": "NI",
    "niger": "NE",
    "nigeria": "NG",
    "niué": "NU",
    "norfolk": "NF",
    "norvège": "NO",
    "nouvelle-zélande": "NZ",
    "oman": "OM",
    "ouvelle-calédonie": "NC",
    "pakistan": "PK",
    "palaos": "PW",
    "palestine": "PS",
    "panama": "PA",
    "papouasie-nouvelle guinée": "PG",
    "paraguay": "PY",
    "pays-bas": "NL",
    "pérou": "PE",
    "philippines": "PH",
    "pitcairn": "PN",
    "pologne": "PL",
    "polynésie française": "PF",
    "porto rico": "PR",
    "portugal": "PT",
    "qatar": "QA",
    "république tchèque": "CZ",
    "réunion": "RE",
    "roumanie": "RO",
    "russie": "RU",
    "rwanda": "RW",
    "saint-christophe-et-niévès": "KN",
    "saint-marin": "SM",
    "saint-pierre-et-miquelon": "PM",
    "saint-vincent-et-les-grenadines": "VC",
    "sainte-hélène, île": "SH",
    "sainte-lucie": "LC",
    "salvador": "SV",
    "samoa américaines": "AS",
    "sao tomé-et-principe": "ST",
    "sénégal": "SN",
    "serbie": "RS",
    "seychelles": "SC",
    "sierra leone": "SL",
    "singapour": "SG",
    "slovaquie": "SK",
    "sri lanka": "LK",
    "taïwan / (république de chine)": "TW",
    "tchad": "TD",
    "terres australes et antarctiques françaises": "TF",
    "territoire britannique de l'océan indien": "IO",
    "timor oriental": "TL",
    "vanuatu": "VU",
    "vatican / (saint-siège)": "VA"
}

iso3166_alpha3_to_iso3166_alpha2 = {
    "ABW": "AW",
    "AFG": "AF",
    "AGO": "AO",
    "AIA": "AI",
    "ALA": "AX",
    "ALB": "AL",
    "AND": "AD",
    "ANT": "AN",
    "ARE": "AE",
    "ARG": "AR",
    "ARM": "AM",
    "ASM": "AS",
    "ATA": "AQ",
    "ATF": "TF",
    "ATG": "AG",
    "AUS": "AU",
    "AUT": "AT",
    "AZE": "AZ",
    "BDI": "BI",
    "BEL": "BE",
    "BEN": "BJ",
    "BFA": "BF",
    "BGD": "BD",
    "BGR": "BG",
    "BHR": "BH",
    "BHS": "BS",
    "BIH": "BA",
    "BLR": "BY",
    "BLZ": "BZ",
    "BMU": "BM",
    "BOL": "BO",
    "BRA": "BR",
    "BRB": "BB",
    "BRN": "BN",
    "BTN": "BT",
    "BVT": "BV",
    "BWA": "BW",
    "CAF": "CF",
    "CAN": "CA",
    "CCK": "CC",
    "CHE": "CH",
    "CHL": "CL",
    "CHN": "CN",
    "CIV": "CI",
    "CMR": "CM",
    "COD": "CD",
    "COG": "CG",
    "COK": "CK",
    "COL": "CO",
    "COM": "KM",
    "CPV": "CV",
    "CRI": "CR",
    "CUB": "CU",
    "CXR": "CX",
    "CYM": "KY",
    "CYP": "CY",
    "CZE": "CZ",
    "DEU": "DE",
    "DJI": "DJ",
    "DMA": "DM",
    "DNK": "DK",
    "DOM": "DO",
    "DZA": "DZ",
    "ECU": "EC",
    "EGY": "EG",
    "ERI": "ER",
    "ESH": "EH",
    "ESP": "ES",
    "EST": "EE",
    "ETH": "ET",
    "FIN": "FI",
    "FJI": "FJ",
    "FLK": "FK",
    "FRA": "FR",
    "FRO": "FO",
    "FSM": "FM",
    "GAB": "GA",
    "GBR": "GB",
    "GEO": "GE",
    "GGY": "GG",
    "GHA": "GH",
    "GIB": "GI",
    "GIN": "GN",
    "GLP": "GP",
    "GMB": "GM",
    "GNB": "GW",
    "GNQ": "GQ",
    "GRC": "GR",
    "GRD": "GD",
    "GRL": "GL",
    "GTM": "GT",
    "GUF": "GF",
    "GUM": "GU",
    "GUY": "GY",
    "HKG": "HK",
    "HMD": "HM",
    "HND": "HN",
    "HRV": "HR",
    "HTI": "HT",
    "HUN": "HU",
    "IDN": "ID",
    "IMN": "IM",
    "IND": "IN",
    "IOT": "IO",
    "IRL": "IE",
    "IRN": "IR",
    "IRQ": "IQ",
    "ISL": "IS",
    "ISR": "IL",
    "ITA": "IT",
    "JAM": "JM",
    "JEY": "JE",
    "JOR": "JO",
    "JPN": "JP",
    "KAZ": "KZ",
    "KEN": "KE",
    "KGZ": "KG",
    "KHM": "KH",
    "KIR": "KI",
    "KNA": "KN",
    "KOR": "KR",
    "KWT": "KW",
    "LAO": "LA",
    "LBN": "LB",
    "LBR": "LR",
    "LBY": "LY",
    "LCA": "LC",
    "LIE": "LI",
    "LKA": "LK",
    "LSO": "LS",
    "LTU": "LT",
    "LUX": "LU",
    "LVA": "LV",
    "MAC": "MO",
    "MAR": "MA",
    "MCO": "MC",
    "MDA": "MD",
    "MDG": "MG",
    "MDV": "MV",
    "MEX": "MX",
    "MHL": "MH",
    "MKD": "MK",
    "MLI": "ML",
    "MLT": "MT",
    "MMR": "MM",
    "MNE": "ME",
    "MNG": "MN",
    "MNP": "MP",
    "MOZ": "MZ",
    "MRT": "MR",
    "MSR": "MS",
    "MTQ": "MQ",
    "MUS": "MU",
    "MWI": "MW",
    "MYS": "MY",
    "MYT": "YT",
    "NAM": "NA",
    "NCL": "NC",
    "NER": "NE",
    "NFK": "NF",
    "NGA": "NG",
    "NIC": "NI",
    "NIU": "NU",
    "NLD": "NL",
    "NOR": "NO",
    "NPL": "NP",
    "NRU": "NR",
    "NZL": "NZ",
    "OMN": "OM",
    "PAK": "PK",
    "PAN": "PA",
    "PCN": "PN",
    "PER": "PE",
    "PHL": "PH",
    "PLW": "PW",
    "PNG": "PG",
    "POL": "PL",
    "PRI": "PR",
    "PRK": "KP",
    "PRT": "PT",
    "PRY": "PY",
    "PSE": "PS",
    "PYF": "PF",
    "QAT": "QA",
    "REU": "RE",
    "ROU": "RO",
    "RUS": "RU",
    "RWA": "RW",
    "SAU": "SA",
    "SDN": "SD",
    "SEN": "SN",
    "SGP": "SG",
    "SGS": "GS",
    "SHN": "SH",
    "SJM": "SJ",
    "SLB": "SB",
    "SLE": "SL",
    "SLV": "SV",
    "SMR": "SM",
    "SOM": "SO",
    "SPM": "PM",
    "SRB": "RS",
    "STP": "ST",
    "SUR": "SR",
    "SVK": "SK",
    "SVN": "SI",
    "SWE": "SE",
    "SWZ": "SZ",
    "SYC": "SC",
    "SYR": "SY",
    "TCA": "TC",
    "TCD": "TD",
    "TGO": "TG",
    "THA": "TH",
    "TJK": "TJ",
    "TKL": "TK",
    "TKM": "TM",
    "TLS": "TL",
    "TON": "TO",
    "TTO": "TT",
    "TUN": "TN",
    "TUR": "TR",
    "TUV": "TV",
    "TWN": "TW",
    "TZA": "TZ",
    "UGA": "UG",
    "UKR": "UA",
    "UMI": "UM",
    "URY": "UY",
    "USA": "US",
    "UZB": "UZ",
    "VAT": "VA",
    "VCT": "VC",
    "VEN": "VE",
    "VGB": "VG",
    "VIR": "VI",
    "VNM": "VN",
    "VUT": "VU",
    "WLF": "WF",
    "WSM": "WS",
    "YEM": "YE",
    "ZAF": "ZA",
    "ZMB": "ZM",
    "ZWE": "ZW"
}

iso3166_numeric_to_iso3166_alpha2 = {
    "4": "AF",
    "8": "AL",
    "10": "AQ",
    "12": "DZ",
    "16": "AS",
    "20": "AD",
    "24": "AO",
    "28": "AG",
    "31": "AZ",
    "32": "AR",
    "36": "AU",
    "40": "AT",
    "44": "BS",
    "48": "BH",
    "50": "BD",
    "51": "AM",
    "52": "BB",
    "56": "BE",
    "60": "BM",
    "64": "BT",
    "68": "BO",
    "70": "BA",
    "72": "BW",
    "74": "BV",
    "76": "BR",
    "84": "BZ",
    "86": "IO",
    "90": "SB",
    "92": "VG",
    "96": "BN",
    "100": "BG",
    "104": "MM",
    "108": "BI",
    "112": "BY",
    "116": "KH",
    "120": "CM",
    "124": "CA",
    "132": "CV",
    "136": "KY",
    "140": "CF",
    "144": "LK",
    "148": "TD",
    "152": "CL",
    "156": "CN",
    "158": "TW",
    "162": "CX",
    "166": "CC",
    "170": "CO",
    "174": "KM",
    "175": "YT",
    "178": "CG",
    "180": "CD",
    "184": "CK",
    "188": "CR",
    "191": "HR",
    "192": "CU",
    "196": "CY",
    "203": "CZ",
    "204": "BJ",
    "208": "DK",
    "212": "DM",
    "214": "DO",
    "218": "EC",
    "222": "SV",
    "226": "GQ",
    "231": "ET",
    "232": "ER",
    "233": "EE",
    "234": "FO",
    "238": "FK",
    "239": "GS",
    "242": "FJ",
    "246": "FI",
    "248": "AX",
    "250": "FR",
    "254": "GF",
    "258": "PF",
    "260": "TF",
    "262": "DJ",
    "266": "GA",
    "268": "GE",
    "270": "GM",
    "275": "PS",
    "276": "DE",
    "288": "GH",
    "292": "GI",
    "296": "KI",
    "300": "GR",
    "304": "GL",
    "308": "GD",
    "312": "GP",
    "316": "GU",
    "320": "GT",
    "324": "GN",
    "328": "GY",
    "332": "HT",
    "334": "HM",
    "336": "VA",
    "340": "HN",
    "344": "HK",
    "348": "HU",
    "352": "IS",
    "356": "IN",
    "360": "ID",
    "364": "IR",
    "368": "IQ",
    "372": "IE",
    "376": "IL",
    "380": "IT",
    "384": "CI",
    "388": "JM",
    "392": "JP",
    "398": "KZ",
    "400": "JO",
    "404": "KE",
    "408": "KP",
    "410": "KR",
    "414": "KW",
    "417": "KG",
    "418": "LA",
    "422": "LB",
    "426": "LS",
    "428": "LV",
    "430": "LR",
    "434": "LY",
    "438": "LI",
    "440": "LT",
    "442": "LU",
    "446": "MO",
    "450": "MG",
    "454": "MW",
    "458": "MY",
    "462": "MV",
    "466": "ML",
    "470": "MT",
    "474": "MQ",
    "478": "MR",
    "480": "MU",
    "484": "MX",
    "492": "MC",
    "496": "MN",
    "498": "MD",
    "499": "ME",
    "500": "MS",
    "504": "MA",
    "508": "MZ",
    "512": "OM",
    "516": "NA",
    "520": "NR",
    "524": "NP",
    "528": "NL",
    "530": "AN",
    "533": "AW",
    "540": "NC",
    "548": "VU",
    "554": "NZ",
    "558": "NI",
    "562": "NE",
    "566": "NG",
    "570": "NU",
    "574": "NF",
    "578": "NO",
    "580": "MP",
    "581": "UM",
    "583": "FM",
    "584": "MH",
    "585": "PW",
    "586": "PK",
    "591": "PA",
    "598": "PG",
    "600": "PY",
    "604": "PE",
    "608": "PH",
    "612": "PN",
    "616": "PL",
    "620": "PT",
    "624": "GW",
    "626": "TL",
    "630": "PR",
    "634": "QA",
    "638": "RE",
    "642": "RO",
    "643": "RU",
    "646": "RW",
    "654": "SH",
    "659": "KN",
    "660": "AI",
    "662": "LC",
    "666": "PM",
    "670": "VC",
    "674": "SM",
    "678": "ST",
    "682": "SA",
    "686": "SN",
    "688": "RS",
    "690": "SC",
    "694": "SL",
    "702": "SG",
    "703": "SK",
    "704": "VN",
    "705": "SI",
    "706": "SO",
    "710": "ZA",
    "716": "ZW",
    "724": "ES",
    "732": "EH",
    "736": "SD",
    "740": "SR",
    "744": "SJ",
    "748": "SZ",
    "752": "SE",
    "756": "CH",
    "760": "SY",
    "762": "TJ",
    "764": "TH",
    "768": "TG",
    "772": "TK",
    "776": "TO",
    "780": "TT",
    "784": "AE",
    "788": "TN",
    "792": "TR",
    "795": "TM",
    "796": "TC",
    "798": "TV",
    "800": "UG",
    "804": "UA",
    "807": "MK",
    "818": "EG",
    "826": "GB",
    "831": "GG",
    "832": "JE",
    "833": "IM",
    "834": "TZ",
    "840": "US",
    "850": "VI",
    "854": "BF",
    "858": "UY",
    "860": "UZ",
    "862": "VE",
    "876": "WF",
    "882": "WS",
    "887": "YE",
    "894": "ZM"
}
