#!/usr/bin/python
# -*- coding: utf-8 -*-
# coding=utf-8

import logging

iso639_1_to_iso639_2b = {
    "aa": "aar",
    "ab": "abk",
    "ae": "ave",
    "af": "afr",
    "ak": "aka",
    "am": "amh",
    "an": "arg",
    "ar": "ara",
    "as": "asm",
    "av": "ava",
    "ay": "aym",
    "az": "aze",
    "ba": "bak",
    "be": "bel",
    "bg": "bul",
    "bh": "bih",
    "bi": "bis",
    "bm": "bam",
    "bn": "ben",
    "bo": "tib",
    "br": "bre",
    "bs": "bos",
    "ca": "cat",
    "ce": "che",
    "ch": "cha",
    "co": "cos",
    "cr": "cre",
    "cs": "cze",
    "cu": "chu",
    "cv": "chv",
    "cy": "wel",
    "da": "dan",
    "de": "ger",
    "dv": "div",
    "dz": "dzo",
    "ee": "ewe",
    "el": "gre",
    "en": "eng",
    "eo": "epo",
    "es": "spa",
    "et": "est",
    "eu": "baq",
    "fa": "per",
    "ff": "ful",
    "fi": "fin",
    "fj": "fij",
    "fo": "fao",
    "fr": "fre",
    "fy": "fry",
    "ga": "gle",
    "gd": "gla",
    "gl": "glg",
    "gn": "grn",
    "gu": "guj",
    "gv": "glv",
    "ha": "hau",
    "he": "heb",
    "hi": "hin",
    "ho": "hmo",
    "hr": "scr",
    "ht": "hat",
    "hu": "hun",
    "hy": "arm",
    "hz": "her",
    "ia": "ina",
    "id": "ind",
    "ie": "ile",
    "ig": "ibo",
    "ii": "iii",
    "ik": "ipk",
    "io": "ido",
    "is": "ice",
    "it": "ita",
    "iu": "iku",
    "ja": "jpn",
    "jv": "jav",
    "ka": "geo",
    "kg": "kon",
    "ki": "kik",
    "kj": "kua",
    "kk": "kaz",
    "kl": "kal",
    "km": "khm",
    "kn": "kan",
    "ko": "kor",
    "kr": "kau",
    "ks": "kas",
    "ku": "kur",
    "kv": "kom",
    "kw": "cor",
    "ky": "kir",
    "la": "lat",
    "lb": "ltz",
    "lg": "lug",
    "li": "lim",
    "ln": "lin",
    "lo": "lao",
    "lt": "lit",
    "lu": "lub",
    "lv": "lav",
    "mg": "mlg",
    "mh": "mah",
    "mi": "mao",
    "mk": "mac",
    "ml": "mal",
    "mn": "mon",
    "mr": "mar",
    "ms": "may",
    "mt": "mlt",
    "my": "bur",
    "na": "nau",
    "nb": "nob",
    "nd": "nde",
    "ne": "nep",
    "ng": "ndo",
    "nl": "dut",
    "nn": "nno",
    "no": "nor",
    "nr": "nbl",
    "nv": "nav",
    "ny": "nya",
    "oc": "oci",
    "oj": "oji",
    "om": "orm",
    "or": "ori",
    "os": "oss",
    "pa": "pan",
    "pi": "pli",
    "pl": "pol",
    "ps": "pus",
    "pt": "por",
    "qu": "que",
    "rm": "roh",
    "rn": "run",
    "ro": "rum",
    "ru": "rus",
    "rw": "kin",
    "sa": "san",
    "sc": "srd",
    "sd": "snd",
    "se": "sme",
    "sg": "sag",
    "si": "sin",
    "sk": "slo",
    "sl": "slv",
    "sm": "smo",
    "sn": "sna",
    "so": "som",
    "sq": "alb",
    "sr": "srp",
    "ss": "ssw",
    "st": "sot",
    "su": "sun",
    "sv": "swe",
    "sw": "swa",
    "ta": "tam",
    "te": "tel",
    "tg": "tgk",
    "th": "tha",
    "ti": "tir",
    "tk": "tuk",
    "tl": "tgl",
    "tn": "tsn",
    "to": "ton",
    "tr": "tur",
    "ts": "tso",
    "tt": "tat",
    "tw": "twi",
    "ty": "tah",
    "ug": "uig",
    "uk": "ukr",
    "ur": "urd",
    "uz": "uzb",
    "ve": "ven",
    "vi": "vie",
    "vo": "vol",
    "wa": "wln",
    "wo": "wol",
    "xh": "xho",
    "yi": "yid",
    "yo": "yor",
    "za": "zha",
    "zh": "chi",
    "zu": "zul"
}

iso639_2b_to_iso639_1 = {
    "aar": "aa",
    "abk": "ab",
    "afr": "af",
    "aka": "ak",
    "alb": "sq",
    "amh": "am",
    "ara": "ar",
    "arg": "an",
    "arm": "hy",
    "asm": "as",
    "ava": "av",
    "ave": "ae",
    "aym": "ay",
    "aze": "az",
    "bak": "ba",
    "bam": "bm",
    "baq": "eu",
    "bel": "be",
    "ben": "bn",
    "bih": "bh",
    "bis": "bi",
    "bos": "bs",
    "bre": "br",
    "bul": "bg",
    "bur": "my",
    "cat": "ca",
    "cha": "ch",
    "che": "ce",
    "chi": "zh",
    "chu": "cu",
    "chv": "cv",
    "cor": "kw",
    "cos": "co",
    "cre": "cr",
    "cze": "cs",
    "dan": "da",
    "div": "dv",
    "dut": "nl",
    "dzo": "dz",
    "eng": "en",
    "epo": "eo",
    "est": "et",
    "ewe": "ee",
    "fao": "fo",
    "fij": "fj",
    "fin": "fi",
    "fre": "fr",
    "fry": "fy",
    "ful": "ff",
    "geo": "ka",
    "ger": "de",
    "gla": "gd",
    "gle": "ga",
    "glg": "gl",
    "glv": "gv",
    "gre": "el",
    "grn": "gn",
    "guj": "gu",
    "hat": "ht",
    "hau": "ha",
    "heb": "he",
    "her": "hz",
    "hin": "hi",
    "hmo": "ho",
    "hun": "hu",
    "ibo": "ig",
    "ice": "is",
    "ido": "io",
    "iii": "ii",
    "iku": "iu",
    "ile": "ie",
    "ina": "ia",
    "ind": "id",
    "ipk": "ik",
    "ita": "it",
    "jav": "jv",
    "jpn": "ja",
    "kal": "kl",
    "kan": "kn",
    "kas": "ks",
    "kau": "kr",
    "kaz": "kk",
    "khm": "km",
    "kik": "ki",
    "kin": "rw",
    "kir": "ky",
    "kom": "kv",
    "kon": "kg",
    "kor": "ko",
    "kua": "kj",
    "kur": "ku",
    "lao": "lo",
    "lat": "la",
    "lav": "lv",
    "lim": "li",
    "lin": "ln",
    "lit": "lt",
    "ltz": "lb",
    "lub": "lu",
    "lug": "lg",
    "mac": "mk",
    "mah": "mh",
    "mal": "ml",
    "mao": "mi",
    "mar": "mr",
    "may": "ms",
    "mlg": "mg",
    "mlt": "mt",
    "mon": "mn",
    "nau": "na",
    "nav": "nv",
    "nbl": "nr",
    "nde": "nd",
    "ndo": "ng",
    "nep": "ne",
    "nno": "nn",
    "nob": "nb",
    "nor": "no",
    "nya": "ny",
    "oci": "oc",
    "oji": "oj",
    "ori": "or",
    "orm": "om",
    "oss": "os",
    "pan": "pa",
    "per": "fa",
    "pli": "pi",
    "pol": "pl",
    "por": "pt",
    "pus": "ps",
    "que": "qu",
    "roh": "rm",
    "rum": "ro",
    "run": "rn",
    "rus": "ru",
    "sag": "sg",
    "san": "sa",
    "scr": "hr",
    "sin": "si",
    "slo": "sk",
    "slv": "sl",
    "sme": "se",
    "smo": "sm",
    "sna": "sn",
    "snd": "sd",
    "som": "so",
    "sot": "st",
    "spa": "es",
    "srd": "sc",
    "srp": "sr",
    "ssw": "ss",
    "sun": "su",
    "swa": "sw",
    "swe": "sv",
    "tah": "ty",
    "tam": "ta",
    "tat": "tt",
    "tel": "te",
    "tgk": "tg",
    "tgl": "tl",
    "tha": "th",
    "tib": "bo",
    "tir": "ti",
    "ton": "to",
    "tsn": "tn",
    "tso": "ts",
    "tuk": "tk",
    "tur": "tr",
    "twi": "tw",
    "uig": "ug",
    "ukr": "uk",
    "urd": "ur",
    "uzb": "uz",
    "ven": "ve",
    "vie": "vi",
    "vol": "vo",
    "wel": "cy",
    "wln": "wa",
    "wol": "wo",
    "xho": "xh",
    "yid": "yi",
    "yor": "yo",
    "zha": "za",
    "zul": "zu"
}

iso639_2b_to_rfc5646 = {
    "aar": "aa",
    "abk": "ab",
    "ace": "ace",
    "ach": "ach",
    "ada": "ada",
    "ady": "ady",
    "afa": "afa",
    "afh": "afh",
    "afr": "af",
    "ain": "ain",
    "aka": "ak",
    "akk": "akk",
    "alb": "sq",
    "ale": "ale",
    "alg": "alg",
    "alt": "alt",
    "amh": "am",
    "ang": "ang",
    "anp": "anp",
    "apa": "apa",
    "ara": "ar",
    "arc": "arc",
    "arg": "an",
    "arm": "hy",
    "arn": "arn",
    "arp": "arp",
    "art": "art",
    "arw": "arw",
    "asm": "as",
    "ast": "ast",
    "ath": "ath",
    "aus": "aus",
    "ava": "av",
    "ave": "ae",
    "awa": "awa",
    "aym": "ay",
    "aze": "az",
    "bad": "bad",
    "bai": "bai",
    "bak": "ba",
    "bal": "bal",
    "bam": "bm",
    "ban": "ban",
    "baq": "eu",
    "bas": "bas",
    "bat": "bat",
    "bej": "bej",
    "bel": "be",
    "bem": "bem",
    "ben": "bn",
    "ber": "ber",
    "bho": "bho",
    "bih": "bh",
    "bik": "bik",
    "bin": "bin",
    "bis": "bi",
    "bla": "bla",
    "bnt": "bnt",
    "bos": "bs",
    "bra": "bra",
    "bre": "br",
    "btk": "btk",
    "bua": "bua",
    "bug": "bug",
    "bul": "bg",
    "bur": "my",
    "byn": "byn",
    "cad": "cad",
    "cai": "cai",
    "car": "car",
    "cat": "ca",
    "cau": "cau",
    "ceb": "ceb",
    "cel": "cel",
    "cha": "ch",
    "chb": "chb",
    "che": "ce",
    "chg": "chg",
    "chi": "zh",
    "chk": "chk",
    "chm": "chm",
    "chn": "chn",
    "cho": "cho",
    "chp": "chp",
    "chr": "chr",
    "chu": "cu",
    "chv": "cv",
    "chy": "chy",
    "cmc": "cmc",
    "cop": "cop",
    "cor": "kw",
    "cos": "co",
    "cpe": "cpe",
    "cpf": "cpf",
    "cpp": "cpp",
    "cre": "cr",
    "crh": "crh",
    "crp": "crp",
    "csb": "csb",
    "cus": "cus",
    "cze": "cs",
    "dak": "dak",
    "dan": "da",
    "dar": "dar",
    "day": "day",
    "del": "del",
    "den": "den",
    "dgr": "dgr",
    "din": "din",
    "div": "dv",
    "doi": "doi",
    "dra": "dra",
    "dsb": "dsb",
    "dua": "dua",
    "dum": "dum",
    "dut": "nl",
    "dyu": "dyu",
    "dzo": "dz",
    "efi": "efi",
    "egy": "egy",
    "eka": "eka",
    "elx": "elx",
    "eng": "en",
    "enm": "enm",
    "epo": "eo",
    "est": "et",
    "ewe": "ee",
    "ewo": "ewo",
    "fan": "fan",
    "fao": "fo",
    "fat": "fat",
    "fij": "fj",
    "fil": "fil",
    "fin": "fi",
    "fiu": "fiu",
    "fon": "fon",
    "fre": "fr",
    "frm": "frm",
    "fro": "fro",
    "frr": "frr",
    "frs": "frs",
    "fry": "fy",
    "ful": "ff",
    "fur": "fur",
    "gaa": "gaa",
    "gay": "gay",
    "gba": "gba",
    "gem": "gem",
    "geo": "ka",
    "ger": "de",
    "gez": "gez",
    "gil": "gil",
    "gla": "gd",
    "gle": "ga",
    "glg": "gl",
    "glv": "gv",
    "gmh": "gmh",
    "goh": "goh",
    "gon": "gon",
    "gor": "gor",
    "got": "got",
    "grb": "grb",
    "grc": "grc",
    "gre": "el",
    "grn": "gn",
    "gsw": "gsw",
    "guj": "gu",
    "gwi": "gwi",
    "hai": "hai",
    "hat": "ht",
    "hau": "ha",
    "haw": "haw",
    "heb": "he",
    "her": "hz",
    "hil": "hil",
    "him": "him",
    "hin": "hi",
    "hit": "hit",
    "hmn": "hmn",
    "hmo": "ho",
    "hsb": "hsb",
    "hun": "hu",
    "hup": "hup",
    "iba": "iba",
    "ibo": "ig",
    "ice": "is",
    "ido": "io",
    "iii": "ii",
    "ijo": "ijo",
    "iku": "iu",
    "ile": "ie",
    "ilo": "ilo",
    "ina": "ia",
    "inc": "inc",
    "ind": "id",
    "ine": "ine",
    "inh": "inh",
    "ipk": "ik",
    "ira": "ira",
    "iro": "iro",
    "ita": "it",
    "jav": "jv",
    "jbo": "jbo",
    "jpn": "ja",
    "jpr": "jpr",
    "jrb": "jrb",
    "kaa": "kaa",
    "kab": "kab",
    "kac": "kac",
    "kal": "kl",
    "kam": "kam",
    "kan": "kn",
    "kar": "kar",
    "kas": "ks",
    "kau": "kr",
    "kaw": "kaw",
    "kaz": "kk",
    "kbd": "kbd",
    "kha": "kha",
    "khi": "khi",
    "khm": "km",
    "kho": "kho",
    "kik": "ki",
    "kin": "rw",
    "kir": "ky",
    "kmb": "kmb",
    "kok": "kok",
    "kom": "kv",
    "kon": "kg",
    "kor": "ko",
    "kos": "kos",
    "kpe": "kpe",
    "krc": "krc",
    "krl": "krl",
    "kro": "kro",
    "kru": "kru",
    "kua": "kj",
    "kum": "kum",
    "kur": "ku",
    "kut": "kut",
    "lad": "lad",
    "lah": "lah",
    "lam": "lam",
    "lao": "lo",
    "lat": "la",
    "lav": "lv",
    "lez": "lez",
    "lim": "li",
    "lin": "ln",
    "lit": "lt",
    "lol": "lol",
    "loz": "loz",
    "ltz": "lb",
    "lua": "lua",
    "lub": "lu",
    "lug": "lg",
    "lui": "lui",
    "lun": "lun",
    "luo": "luo",
    "lus": "lus",
    "mac": "mk",
    "mad": "mad",
    "mag": "mag",
    "mah": "mh",
    "mai": "mai",
    "mak": "mak",
    "mal": "ml",
    "man": "man",
    "mao": "mi",
    "map": "map",
    "mar": "mr",
    "mas": "mas",
    "may": "ms",
    "mdf": "mdf",
    "mdr": "mdr",
    "men": "men",
    "mga": "mga",
    "mic": "mic",
    "min": "min",
    "mis": "mis",
    "mkh": "mkh",
    "mlg": "mg",
    "mlt": "mt",
    "mnc": "mnc",
    "mni": "mni",
    "mno": "mno",
    "moh": "moh",
    "mon": "mn",
    "mos": "mos",
    "mul": "mul",
    "mun": "mun",
    "mus": "mus",
    "mwl": "mwl",
    "mwr": "mwr",
    "myn": "myn",
    "myv": "myv",
    "nah": "nah",
    "nai": "nai",
    "nap": "nap",
    "nau": "na",
    "nav": "nv",
    "nbl": "nr",
    "nde": "nd",
    "ndo": "ng",
    "nds": "nds",
    "nep": "ne",
    "new": "new",
    "nia": "nia",
    "nic": "nic",
    "niu": "niu",
    "nno": "nn",
    "nob": "nb",
    "nog": "nog",
    "non": "non",
    "nor": "no",
    "nqo": "nqo",
    "nso": "nso",
    "nub": "nub",
    "nwc": "nwc",
    "nya": "ny",
    "nym": "nym",
    "nyn": "nyn",
    "nyo": "nyo",
    "nzi": "nzi",
    "oci": "oc",
    "oji": "oj",
    "ori": "or",
    "orm": "om",
    "osa": "osa",
    "oss": "os",
    "ota": "ota",
    "oto": "oto",
    "paa": "paa",
    "pag": "pag",
    "pal": "pal",
    "pam": "pam",
    "pan": "pa",
    "pap": "pap",
    "pau": "pau",
    "peo": "peo",
    "per": "fa",
    "phi": "phi",
    "phn": "phn",
    "pli": "pi",
    "pol": "pl",
    "pon": "pon",
    "por": "pt",
    "pra": "pra",
    "pro": "pro",
    "pus": "ps",
    "qaa/qtz": "qaa/qtz",  # local-use
    "que": "qu",
    "raj": "raj",
    "rap": "rap",
    "rar": "rar",
    "roa": "roa",
    "roh": "rm",
    "rom": "rom",
    "rum": "ro",
    "run": "rn",
    "rup": "rup",
    "rus": "ru",
    "sad": "sad",
    "sag": "sg",
    "sah": "sah",
    "sai": "sai",
    "sal": "sal",
    "sam": "sam",
    "san": "sa",
    "sas": "sas",
    "sat": "sat",
    "scn": "scn",
    "sco": "sco",
    "scr": "hr",
    "sel": "sel",
    "sem": "sem",
    "sga": "sga",
    "sgn": "sgn",
    "shn": "shn",
    "sid": "sid",
    "sin": "si",
    "sio": "sio",
    "sit": "sit",
    "sla": "sla",
    "slo": "sk",
    "slv": "sl",
    "sma": "sma",
    "sme": "se",
    "smi": "smi",
    "smj": "smj",
    "smn": "smn",
    "smo": "sm",
    "sms": "sms",
    "sna": "sn",
    "snd": "sd",
    "snk": "snk",
    "sog": "sog",
    "som": "so",
    "son": "son",
    "sot": "st",
    "spa": "es",
    "srd": "sc",
    "srn": "srn",
    "srp": "sr",
    "srr": "srr",
    "ssa": "ssa",
    "ssw": "ss",
    "suk": "suk",
    "sun": "su",
    "sus": "sus",
    "sux": "sux",
    "swa": "sw",
    "swe": "sv",
    "syc": "syc",
    "syr": "syr",
    "tah": "ty",
    "tai": "tai",
    "tam": "ta",
    "tat": "tt",
    "tel": "te",
    "tem": "tem",
    "ter": "ter",
    "tet": "tet",
    "tgk": "tg",
    "tgl": "tl",
    "tha": "th",
    "tib": "bo",
    "tig": "tig",
    "tir": "ti",
    "tiv": "tiv",
    "tkl": "tkl",
    "tlh": "tlh",
    "tli": "tli",
    "tmh": "tmh",
    "tog": "tog",
    "ton": "to",
    "tpi": "tpi",
    "tsi": "tsi",
    "tsn": "tn",
    "tso": "ts",
    "tuk": "tk",
    "tum": "tum",
    "tup": "tup",
    "tur": "tr",
    "tut": "tut",
    "tvl": "tvl",
    "twi": "tw",
    "tyv": "tyv",
    "udm": "udm",
    "uga": "uga",
    "uig": "ug",
    "ukr": "uk",
    "umb": "umb",
    "und": "und",
    "urd": "ur",
    "uzb": "uz",
    "vai": "vai",
    "ven": "ve",
    "vie": "vi",
    "vol": "vo",
    "vot": "vot",
    "wak": "wak",
    "wal": "wal",
    "war": "war",
    "was": "was",
    "wel": "cy",
    "wen": "wen",
    "wln": "wa",
    "wol": "wo",
    "xal": "xal",
    "xho": "xh",
    "yao": "yao",
    "yap": "yap",
    "yid": "yi",
    "yor": "yo",
    "ypk": "ypk",
    "zap": "zap",
    "zbl": "zbl",
    "zen": "zen",
    "zha": "za",
    "znd": "znd",
    "zul": "zu",
    "zun": "zun",
    "zxx": "zxx",
    "zza": "zza"
}

iso639_2t_to_iso639_2b = {
    "aar": "aar",
    "abk": "abk",
    "ace": "ace",
    "ach": "ach",
    "ada": "ada",
    "ady": "ady",
    "afh": "afh",
    "afr": "afr",
    "ain": "ain",
    "aka": "aka",
    "akk": "akk",
    "ale": "ale",
    "alt": "alt",
    "amh": "amh",
    "ang": "ang",
    "anp": "anp",
    "ara": "ara",
    "arc": "arc",
    "arg": "arg",
    "arn": "arn",
    "arp": "arp",
    "arw": "arw",
    "asm": "asm",
    "ast": "ast",
    "ava": "ava",
    "ave": "ave",
    "awa": "awa",
    "aym": "aym",
    "aze": "aze",
    "bak": "bak",
    "bal": "bal",
    "bam": "bam",
    "ban": "ban",
    "bas": "bas",
    "bej": "bej",
    "bel": "bel",
    "bem": "bem",
    "ben": "ben",
    "bho": "bho",
    "bik": "bik",
    "bin": "bin",
    "bis": "bis",
    "bla": "bla",
    "bod": "tib",
    "bos": "bos",
    "bra": "bra",
    "bre": "bre",
    "bua": "bua",
    "bug": "bug",
    "bul": "bul",
    "byn": "byn",
    "cad": "cad",
    "car": "car",
    "cat": "cat",
    "ceb": "ceb",
    "ces": "cze",
    "cha": "cha",
    "chb": "chb",
    "che": "che",
    "chg": "chg",
    "chk": "chk",
    "chm": "chm",
    "chn": "chn",
    "cho": "cho",
    "chp": "chp",
    "chr": "chr",
    "chu": "chu",
    "chv": "chv",
    "chy": "chy",
    "cop": "cop",
    "cor": "cor",
    "cos": "cos",
    "cre": "cre",
    "crh": "crh",
    "csb": "csb",
    "cym": "wel",
    "dak": "dak",
    "dan": "dan",
    "dar": "dar",
    "del": "del",
    "den": "den",
    "deu": "ger",
    "dgr": "dgr",
    "din": "din",
    "div": "div",
    "doi": "doi",
    "dsb": "dsb",
    "dua": "dua",
    "dum": "dum",
    "dyu": "dyu",
    "dzo": "dzo",
    "efi": "efi",
    "egy": "egy",
    "eka": "eka",
    "ell": "gre",
    "elx": "elx",
    "eng": "eng",
    "enm": "enm",
    "epo": "epo",
    "est": "est",
    "eus": "baq",
    "ewe": "ewe",
    "ewo": "ewo",
    "fan": "fan",
    "fao": "fao",
    "fas": "per",
    "fat": "fat",
    "fij": "fij",
    "fil": "fil",
    "fin": "fin",
    "fon": "fon",
    "fra": "fre",
    "frm": "frm",
    "fro": "fro",
    "frr": "frr",
    "frs": "frs",
    "fry": "fry",
    "ful": "ful",
    "fur": "fur",
    "gaa": "gaa",
    "gay": "gay",
    "gba": "gba",
    "gez": "gez",
    "gil": "gil",
    "gla": "gla",
    "gle": "gle",
    "glg": "glg",
    "glv": "glv",
    "gmh": "gmh",
    "goh": "goh",
    "gon": "gon",
    "gor": "gor",
    "got": "got",
    "grb": "grb",
    "grc": "grc",
    "grn": "grn",
    "gsw": "gsw",
    "guj": "guj",
    "gwi": "gwi",
    "hai": "hai",
    "hat": "hat",
    "hau": "hau",
    "haw": "haw",
    "heb": "heb",
    "her": "her",
    "hil": "hil",
    "hin": "hin",
    "hit": "hit",
    "hmn": "hmn",
    "hmo": "hmo",
    "hrv": "scr",
    "hsb": "hsb",
    "hun": "hun",
    "hup": "hup",
    "hye": "arm",
    "iba": "iba",
    "ibo": "ibo",
    "ido": "ido",
    "iii": "iii",
    "iku": "iku",
    "ile": "ile",
    "ilo": "ilo",
    "ina": "ina",
    "ind": "ind",
    "inh": "inh",
    "ipk": "ipk",
    "isl": "ice",
    "ita": "ita",
    "jav": "jav",
    "jbo": "jbo",
    "jpn": "jpn",
    "jpr": "jpr",
    "jrb": "jrb",
    "kaa": "kaa",
    "kab": "kab",
    "kac": "kac",
    "kal": "kal",
    "kam": "kam",
    "kan": "kan",
    "kas": "kas",
    "kat": "geo",
    "kau": "kau",
    "kaw": "kaw",
    "kaz": "kaz",
    "kbd": "kbd",
    "kha": "kha",
    "khm": "khm",
    "kho": "kho",
    "kik": "kik",
    "kin": "kin",
    "kir": "kir",
    "kmb": "kmb",
    "kok": "kok",
    "kom": "kom",
    "kon": "kon",
    "kor": "kor",
    "kos": "kos",
    "kpe": "kpe",
    "krc": "krc",
    "krl": "krl"
}

iso639_2t_to_rfc5646 = {
    "aar": "aa",
    "abk": "ab",
    "ace": "ace",
    "ach": "ach",
    "ada": "ada",
    "ady": "ady",
    "afh": "afh",
    "afr": "af",
    "ain": "ain",
    "aka": "ak",
    "akk": "akk",
    "ale": "ale",
    "alt": "alt",
    "amh": "am",
    "ang": "ang",
    "anp": "anp",
    "ara": "ar",
    "arc": "arc",
    "arg": "an",
    "arn": "arn",
    "arp": "arp",
    "arw": "arw",
    "asm": "as",
    "ast": "ast",
    "ava": "av",
    "ave": "ae",
    "awa": "awa",
    "aym": "ay",
    "aze": "az",
    "bak": "ba",
    "bal": "bal",
    "bam": "bm",
    "ban": "ban",
    "bas": "bas",
    "bej": "bej",
    "bel": "be",
    "bem": "bem",
    "ben": "bn",
    "bho": "bho",
    "bik": "bik",
    "bin": "bin",
    "bis": "bi",
    "bla": "bla",
    "bod": "bo",
    "bos": "bs",
    "bra": "bra",
    "bre": "br",
    "bua": "bua",
    "bug": "bug",
    "bul": "bg",
    "byn": "byn",
    "cad": "cad",
    "car": "car",
    "cat": "ca",
    "ceb": "ceb",
    "ces": "cs",
    "cha": "ch",
    "chb": "chb",
    "che": "ce",
    "chg": "chg",
    "chk": "chk",
    "chm": "chm",
    "chn": "chn",
    "cho": "cho",
    "chp": "chp",
    "chr": "chr",
    "chu": "cu",
    "chv": "cv",
    "chy": "chy",
    "cop": "cop",
    "cor": "kw",
    "cos": "co",
    "cre": "cr",
    "crh": "crh",
    "csb": "csb",
    "cym": "cy",
    "dak": "dak",
    "dan": "da",
    "dar": "dar",
    "del": "del",
    "den": "den",
    "deu": "de",
    "dgr": "dgr",
    "din": "din",
    "div": "dv",
    "doi": "doi",
    "dsb": "dsb",
    "dua": "dua",
    "dum": "dum",
    "dyu": "dyu",
    "dzo": "dz",
    "efi": "efi",
    "egy": "egy",
    "eka": "eka",
    "ell": "el",
    "elx": "elx",
    "eng": "en",
    "enm": "enm",
    "epo": "eo",
    "est": "et",
    "eus": "eu",
    "ewe": "ee",
    "ewo": "ewo",
    "fan": "fan",
    "fao": "fo",
    "fas": "fa",
    "fat": "fat",
    "fij": "fj",
    "fil": "fil",
    "fin": "fi",
    "fon": "fon",
    "fra": "fr",
    "frm": "frm",
    "fro": "fro",
    "frr": "frr",
    "frs": "frs",
    "fry": "fy",
    "ful": "ff",
    "fur": "fur",
    "gaa": "gaa",
    "gay": "gay",
    "gba": "gba",
    "gez": "gez",
    "gil": "gil",
    "gla": "gd",
    "gle": "ga",
    "glg": "gl",
    "glv": "gv",
    "gmh": "gmh",
    "goh": "goh",
    "gon": "gon",
    "gor": "gor",
    "got": "got",
    "grb": "grb",
    "grc": "grc",
    "grn": "gn",
    "gsw": "gsw",
    "guj": "gu",
    "gwi": "gwi",
    "hai": "hai",
    "hat": "ht",
    "hau": "ha",
    "haw": "haw",
    "heb": "he",
    "her": "hz",
    "hil": "hil",
    "hin": "hi",
    "hit": "hit",
    "hmn": "hmn",
    "hmo": "ho",
    "hrv": "hr",
    "hsb": "hsb",
    "hun": "hu",
    "hup": "hup",
    "hye": "hy",
    "iba": "iba",
    "ibo": "ig",
    "ido": "io",
    "iii": "ii",
    "iku": "iu",
    "ile": "ie",
    "ilo": "ilo",
    "ina": "ia",
    "ind": "id",
    "inh": "inh",
    "ipk": "ik",
    "isl": "is",
    "ita": "it",
    "jav": "jv",
    "jbo": "jbo",
    "jpn": "ja",
    "jpr": "jpr",
    "jrb": "jrb",
    "kaa": "kaa",
    "kab": "kab",
    "kac": "kac",
    "kal": "kl",
    "kam": "kam",
    "kan": "kn",
    "kas": "ks",
    "kat": "ka",
    "kau": "kr",
    "kaw": "kaw",
    "kaz": "kk",
    "kbd": "kbd",
    "kha": "kha",
    "khm": "km",
    "kho": "kho",
    "kik": "ki",
    "kin": "rw",
    "kir": "ky",
    "kmb": "kmb",
    "kok": "kok",
    "kom": "kv",
    "kon": "kg",
    "kor": "ko",
    "kos": "kos",
    "kpe": "kpe",
    "krc": "krc",
    "krl": "krl",
    "kru": "kru",
    "kua": "kj",
    "kum": "kum",
    "kur": "ku",
    "kut": "kut",
    "lad": "lad",
    "lah": "lah",
    "lam": "lam",
    "lao": "lo",
    "lat": "la",
    "lav": "lv",
    "lez": "lez",
    "lim": "li",
    "lin": "ln",
    "lit": "lt",
    "lol": "lol",
    "loz": "loz",
    "ltz": "lb",
    "lua": "lua",
    "lub": "lu",
    "lug": "lg",
    "lui": "lui",
    "lun": "lun",
    "luo": "luo",
    "lus": "lus",
    "mad": "mad",
    "mag": "mag",
    "mah": "mh",
    "mai": "mai",
    "mak": "mak",
    "mal": "ml",
    "man": "man",
    "mar": "mr",
    "mas": "mas",
    "mdf": "mdf",
    "mdr": "mdr",
    "men": "men",
    "mga": "mga",
    "mic": "mic",
    "min": "min",
    "mis": "mis",
    "mkd": "mk",
    "mlg": "mg",
    "mlt": "mt",
    "mnc": "mnc",
    "mni": "mni",
    "moh": "moh",
    "mon": "mn",
    "mos": "mos",
    "mri": "mi",
    "msa": "ms",
    "mul": "mul",
    "mus": "mus",
    "mwl": "mwl",
    "mwr": "mwr",
    "mya": "my",
    "myv": "myv",
    "nap": "nap",
    "nau": "na",
    "nav": "nv",
    "nbl": "nr",
    "nde": "nd",
    "ndo": "ng",
    "nds": "nds",
    "nep": "ne",
    "new": "new",
    "nia": "nia",
    "niu": "niu",
    "nld": "nl",
    "nno": "nn",
    "nob": "nb",
    "nog": "nog",
    "non": "non",
    "nor": "no",
    "nqo": "nqo",
    "nso": "nso",
    "nwc": "nwc",
    "nya": "ny",
    "nym": "nym",
    "nyn": "nyn",
    "nyo": "nyo",
    "nzi": "nzi",
    "oci": "oc",
    "oji": "oj",
    "ori": "or",
    "orm": "om",
    "osa": "osa",
    "oss": "os",
    "ota": "ota",
    "pag": "pag",
    "pal": "pal",
    "pam": "pam",
    "pan": "pa",
    "pap": "pap",
    "pau": "pau",
    "peo": "peo",
    "phn": "phn",
    "pli": "pi",
    "pol": "pl",
    "pon": "pon",
    "por": "pt",
    "pro": "pro",
    "pus": "ps",
    "que": "qu",
    "raj": "raj",
    "rap": "rap",
    "rar": "rar",
    "roh": "rm",
    "rom": "rom",
    "ron": "ro",
    "run": "rn",
    "rup": "rup",
    "rus": "ru",
    "sad": "sad",
    "sag": "sg",
    "sah": "sah",
    "sam": "sam",
    "san": "sa",
    "sas": "sas",
    "sat": "sat",
    "scn": "scn",
    "sco": "sco",
    "sel": "sel",
    "sga": "sga",
    "shn": "shn",
    "sid": "sid",
    "sin": "si",
    "slk": "sk",
    "slv": "sl",
    "sma": "sma",
    "sme": "se",
    "smj": "smj",
    "smn": "smn",
    "smo": "sm",
    "sms": "sms",
    "sna": "sn",
    "snd": "sd",
    "snk": "snk",
    "sog": "sog",
    "som": "so",
    "sot": "st",
    "spa": "es",
    "sqi": "sq",
    "srd": "sc",
    "srn": "srn",
    "srp": "sr",
    "srr": "srr",
    "ssw": "ss",
    "suk": "suk",
    "sun": "su",
    "sus": "sus",
    "sux": "sux",
    "swa": "sw",
    "swe": "sv",
    "syc": "syc",
    "syr": "syr",
    "tah": "ty",
    "tam": "ta",
    "tat": "tt",
    "tel": "te",
    "tem": "tem",
    "ter": "ter",
    "tet": "tet",
    "tgk": "tg",
    "tgl": "tl",
    "tha": "th",
    "tig": "tig",
    "tir": "ti",
    "tiv": "tiv",
    "tkl": "tkl",
    "tlh": "tlh",
    "tli": "tli",
    "tmh": "tmh",
    "tog": "tog",
    "ton": "to",
    "tpi": "tpi",
    "tsi": "tsi",
    "tsn": "tn",
    "tso": "ts",
    "tuk": "tk",
    "tum": "tum",
    "tur": "tr",
    "tvl": "tvl",
    "twi": "tw",
    "tyv": "tyv",
    "udm": "udm",
    "uga": "uga",
    "uig": "ug",
    "ukr": "uk",
    "umb": "umb",
    "und": "und",
    "urd": "ur",
    "uzb": "uz",
    "vai": "vai",
    "ven": "ve",
    "vie": "vi",
    "vol": "vo",
    "vot": "vot",
    "wal": "wal",
    "war": "war",
    "was": "was",
    "wln": "wa",
    "wol": "wo",
    "xal": "xal",
    "xho": "xh",
    "yao": "yao",
    "yap": "yap",
    "yid": "yi",
    "yor": "yo",
    "zap": "zap",
    "zbl": "zbl",
    "zen": "zen",
    "zha": "za",
    "zho": "zh",
    "zul": "zu",
    "zun": "zun",
    "zxx": "zxx",
    "zza": "zza"
}

french_to_rfc5646 = {
    "abkhaze": "ab",
    "aceh": "ace",
    "acoli": "ach",
    "adangme": "ada",
    "adyghé": "ady",
    "afar": "aa",
    "afrihili": "afh",
    "afrikaans": "af",
    "afro-asiatiques, langues": "afa",
    "aïnou": "ain",
    "akan": "ak",
    "akkadien": "akk",
    "albanais": "sq",
    "alémanique": "gsw",
    "aléoute": "ale",
    "algonquines, langues": "alg",
    "allemand": "de",
    "allemand, bas; bas allemand; saxon, bas; bas saxon": "nds",
    "allemand, moyen haut (ca. 1050-1500)": "gmh",
    "allemand, vieux haut (ca. 750-1050)": "goh",
    "altaï du Sud": "alt",
    "altaïques, autres langues": "tut",
    "amérindiennes de l'Amérique centrale, langues": "cai",
    "amharique": "am",
    "angika": "anp",
    "anglais": "en",
    "anglais moyen (1100-1500)": "enm",
    "anglo-saxon (ca.450-1100)": "ang",
    "apaches, langues": "apa",
    "arabe": "ar",
    "aragonais": "an",
    "araméen d'empire (700-300 BCE)": "arc",
    "arapaho": "arp",
    "arawak": "arw",
    "arménien": "hy",
    "aroumain; macédo-roumain": "rup",
    "artificielles, langues": "art",
    "assamais": "as",
    "asturien; bable; léonais; asturoléonais": "ast",
    "athapascanes, langues": "ath",
    "australiennes, langues": "aus",
    "avar": "av",
    "avestique": "ae",
    "awadhi": "awa",
    "aymara": "ay",
    "azéri": "az",
    "bachkir": "ba",
    "balinais": "ban",
    "baloutchi": "bal",
    "baltes, langues": "bat",
    "bambara": "bm",
    "bamilékés, langues": "bai",
    "banda, langues": "bad",
    "bantoues, langues": "bnt",
    "bas-sorabe": "dsb",
    "basa": "bas",
    "basque": "eu",
    "batak, langues": "btk",
    "bedja": "bej",
    "bemba": "bem",
    "bengali": "bn",
    "berbères, langues": "ber",
    "bhojpuri": "bho",
    "bichlamar": "bi",
    "biélorusse": "be",
    "biharis, langues": "bh",
    "bikol": "bik",
    "bini; edo": "bin",
    "birman": "my",
    "blackfoot": "bla",
    "blin; bilen": "byn",
    "bosniaque": "bs",
    "bouriate": "bua",
    "braj": "bra",
    "breton": "br",
    "bugi": "bug",
    "bulgare": "bg",
    "caddo": "cad",
    "carélien": "krl",
    "catalan; valencien": "ca",
    "caucasiennes, langues": "cau",
    "cebuano": "ceb",
    "celtiques, langues; celtes, langues": "cel",
    "chames, langues": "cmc",
    "chamorro": "ch",
    "chan": "shn",
    "cherokee": "chr",
    "cheyenne": "chy",
    "chibcha": "chb",
    "chichewa; chewa; nyanja": "ny",
    "chinois": "zh",
    "chinook, jargon": "chn",
    "chipewyan": "chp",
    "choctaw": "cho",
    "chuuk": "chk",
    "copte": "cop",
    "coréen": "ko",
    "cornique": "kw",
    "corse": "co",
    "couchitiques, autres langues": "cus",
    "cree": "cr",
    "créoles et pidgins anglais, autres": "cpe",
    "créoles et pidgins divers": "crp",
    "créoles et pidgins français, autres": "cpf",
    "créoles et pidgins portugais, autres": "cpp",
    "croate": "hr",
    "dakota": "dak",
    "danois": "da",
    "dargwa": "dar",
    "dayak, langues": "day",
    "delaware": "del",
    "dinka": "din",
    "dioula": "dyu",
    "diverses, langues": "mis",
    "djaghataï": "chg",
    "dogri": "doi",
    "dogrib": "dgr",
    "douala": "dua",
    "dravidiennes, autres langues": "dra",
    "dzongkha": "dz",
    "écossais": "sco",
    "efik": "efi",
    "égyptien": "egy",
    "ekajuk": "eka",
    "élamite": "elx",
    "erza": "myv",
    "esclave (athapascan)": "den",
    "espagnol; castillan": "es",
    "espéranto": "eo",
    "estonien": "et",
    "éwé": "ee",
    "éwondo": "ewo",
    "fang": "fan",
    "fanti": "fat",
    "féroïen": "fo",
    "fidjien": "fj",
    "filipino; pilipino": "fil",
    "finno-ougriennes, autres langues": "fiu",
    "finnois": "fi",
    "fon": "fon",
    "france": "fr",
    "français": "fr",
    "français ancien (842-ca.1400)": "fro",
    "français moyen (1400-1600)": "frm",
    "frioulan": "fur",
    "frison occidental": "fy",
    "frison oriental": "frs",
    "frison septentrional": "frr",
    "ga": "gaa",
    "gaélique; gaélique écossais": "gd",
    "galicien": "gl",
    "galla": "om",
    "gallois": "cy",
    "ganda": "lg",
    "gayo": "gay",
    "gbaya": "gba",
    "géorgien": "ka",
    "germaniques, autres langues": "gem",
    "gond": "gon",
    "gorontalo": "gor",
    "gothique": "got",
    "goudjrati": "gu",
    "grebo": "grb",
    "grec ancien (jusqu'à 1453)": "grc",
    "grec moderne (après 1453)": "el",
    "groenlandais": "kl",
    "guarani": "gn",
    "guèze": "gez",
    "gwich´in": "gwi",
    "haida": "hai",
    "haïtien; créole haïtien": "ht",
    "haoussa": "ha",
    "haut-sorabe": "hsb",
    "hawaïen": "haw",
    "hébreu": "he",
    "herero": "hz",
    "hiligaynon": "hil",
    "himachali": "him",
    "hindi": "hi",
    "hiri motu": "ho",
    "hittite": "hit",
    "hmong": "hmn",
    "hongrois": "hu",
    "hupa": "hup",
    "iakoute": "sah",
    "iban": "iba",
    "ido": "io",
    "igbo": "ig",
    "ijo, langues": "ijo",
    "ilocano": "ilo",
    "indéterminée": "und",
    "indiennes d'Amérique du Nord, autres langues": "nai",
    "indiennes d'Amérique du Sud, autres langues": "sai",
    "indo-aryennes, autres langues": "inc",
    "indo-européennes, autres langues": "ine",
    "indonésien": "id",
    "ingouche": "inh",
    "interlingua (langue auxiliaire internationale)": "ia",
    "interlingue": "ie",
    "inuktitut": "iu",
    "inupiaq": "ik",
    "iraniennes, autres langues": "ira",
    "irlandais": "ga",
    "irlandais ancien (jusqu'à 900)": "sga",
    "irlandais moyen (900-1200)": "mga",
    "iroquoises, langues (famille)": "iro",
    "islandais": "is",
    "italien": "it",
    "japonais": "ja",
    "javanais": "jv",
    "judéo-arabe": "jrb",
    "judéo-espagnol": "lad",
    "judéo-persan": "jpr",
    "kabardien": "kbd",
    "kabyle": "kab",
    "kachin; jingpho": "kac",
    "kachoube": "csb",
    "kalmouk; oïrat": "xal",
    "kamba": "kam",
    "kannada": "kn",
    "kanouri": "kr",
    "karakalpak": "kaa",
    "karatchai balkar": "krc",
    "karen, langues": "kar",
    "karib; galibi; carib": "car",
    "kashmiri": "ks",
    "kawi": "kaw",
    "kazakh": "kk",
    "khasi": "kha",
    "khmer central": "km",
    "khoisan, autres langues": "khi",
    "khotanais": "kho",
    "kikuyu": "ki",
    "kimbundu": "kmb",
    "kirghiz": "ky",
    "kiribati": "gil",
    "klingon": "tlh",
    "kom": "kv",
    "kongo": "kg",
    "konkani": "kok",
    "kosrae": "kos",
    "koumyk": "kum",
    "kpellé": "kpe",
    "krou, langues": "kro",
    "kuanyama; kwanyama": "kj",
    "kurde": "ku",
    "kurukh": "kru",
    "kutenai": "kut",
    "lahnda": "lah",
    "lamba": "lam",
    "langues des signes": "sgn",
    "lao": "lo",
    "latin": "la",
    "letton": "lv",
    "lezghien": "lez",
    "limbourgeois": "li",
    "lingala": "ln",
    "lituanien": "lt",
    "lojban": "jbo",
    "lozi": "loz",
    "luba-katanga": "lu",
    "luba-lulua": "lua",
    "luiseno": "lui",
    "lunda": "lun",
    "luo (Kenya et Tanzanie)": "luo",
    "lushai": "lus",
    "luxembourgeois": "lb",
    "macédonien": "mk",
    "madourais": "mad",
    "magahi": "mag",
    "maithili": "mai",
    "makassar": "mak",
    "malais": "ms",
    "malayalam": "ml",
    "malayo-polynésiennes, autres langues": "map",
    "maldivien": "dv",
    "malgache": "mg",
    "maltais": "mt",
    "mandar": "mdr",
    "mandchou": "mnc",
    "mandingue": "man",
    "manipuri": "mni",
    "manobo, langues": "mno",
    "manx; mannois": "gv",
    "maori": "mi",
    "mapudungun; mapuche; mapuce": "arn",
    "marathe": "mr",
    "mari": "chm",
    "marshall": "mh",
    "marvari": "mwr",
    "massaï": "mas",
    "maya, langues": "myn",
    "mendé": "men",
    "mi'kmaq; micmac": "mic",
    "minangkabau": "min",
    "mirandais": "mwl",
    "mohawk": "moh",
    "moksa": "mdf",
    "môn-khmer, autres langues": "mkh",
    "mongo": "lol",
    "mongol": "mn",
    "moré": "mos",
    "mounda, langues": "mun",
    "multilingue": "mul",
    "muskogee": "mus",
    "n'ko": "nqo",
    "nahuatl, langues": "nah",
    "napolitain": "nap",
    "nauruan": "na",
    "navaho": "nv",
    "ndébélé du Nord": "nd",
    "ndébélé du Sud": "nr",
    "ndonga": "ng",
    "néerlandais moyen (ca. 1050-1350)": "dum",
    "néerlandais; flamand": "nl",
    "nepal bhasa; newari": "new",
    "népalais": "ne",
    "newari classique": "nwc",
    "nias": "nia",
    "nigéro-congolaises, autres langues": "nic",
    "nilo-sahariennes, autres langues": "ssa",
    "niué": "niu",
    "nogaï; nogay": "nog",
    "norrois, vieux": "non",
    "norvégien": "no",
    "norvégien bokmål": "nb",
    "norvégien nynorsk": "nn",
    "nubiennes, langues": "nub",
    "nyamwezi": "nym",
    "nyankolé": "nyn",
    "nyoro": "nyo",
    "nzema": "nzi",
    "occitan (après 1500); provençal": "oc",
    "ojibwa": "oj",
    "oriya": "or",
    "osage": "osa",
    "ossète": "os",
    "otomangue, langues": "oto",
    "oudmourte": "udm",
    "ougaritique": "uga",
    "ouïgour": "ug",
    "ourdou": "ur",
    "ouszbek": "uz",
    "pachto": "ps",
    "pahlavi": "pal",
    "palau": "pau",
    "pali": "pi",
    "pampangan": "pam",
    "pangasinan": "pag",
    "papiamento": "pap",
    "papoues, autres langues": "paa",
    "pas de contenu linguistique": "zxx",
    "pedi; sepedi; sotho du Nord": "nso",
    "pendjabi": "pa",
    "persan": "fa",
    "perse, vieux (ca. 600-400 av. J.-C.)": "peo",
    "peul": "ff",
    "phénicien": "phn",
    "philippines, autres langues": "phi",
    "pohnpei": "pon",
    "polonais": "pl",
    "portugais": "pt",
    "prâkrit": "pra",
    "provençal ancien (jusqu'à 1500)": "pro",
    "quechua": "qu",
    "rajasthani": "raj",
    "rapanui": "rap",
    "rarotonga; maori des îles Cook": "rar",
    "réservée à l'usage local": "qaa..qtz",
    "romanche": "rm",
    "romanes, autres langues": "roa",
    "roumain": "ro",
    "rundi": "rn",
    "russe": "ru",
    "rwanda": "rw",
    "salish, langues": "sal",
    "samaritain": "sam",
    "sami d'Inari": "smn",
    "sami de Lule": "smj",
    "sami du Nord": "se",
    "sami du Sud": "sma",
    "sami skolt": "sms",
    "sami, autres langues": "smi",
    "samoan": "sm",
    "sandawe": "sad",
    "sango": "sg",
    "sanskrit": "sa",
    "santal": "sat",
    "sarde": "sc",
    "sasak": "sas",
    "selkoupe": "sel",
    "sémitiques, autres langues": "sem",
    "serbe": "sr",
    "sérère": "srr",
    "shona": "sn",
    "sicilien": "scn",
    "sidamo": "sid",
    "sindhi": "sd",
    "singhalais": "si",
    "sino-tibétaines, autres langues": "sit",
    "sioux, langues": "sio",
    "slaves, autres langues": "sla",
    "slavon d'église; vieux slave; slavon liturgique; vieux bulgare": "cu",
    "slovaque": "sk",
    "slovène": "sl",
    "sogdien": "sog",
    "somali": "so",
    "songhai, langues": "son",
    "soninké": "snk",
    "sorabes, langues": "wen",
    "sotho du Sud": "st",
    "soundanais": "su",
    "soussou": "sus",
    "sranan tongo": "srn",
    "suédois": "sv",
    "sukuma": "suk",
    "sumérien": "sux",
    "swahili": "sw",
    "swati": "ss",
    "symboles Bliss, Bliss": "zbl",
    "syriaque": "syr",
    "syriaque classique": "syc",
    "tadjik": "tg",
    "tagalog": "tl",
    "tahitien": "ty",
    "tamacheq": "tmh",
    "tamoul": "ta",
    "tatar": "tt",
    "tatar de Crimé": "crh",
    "tchèque": "cs",
    "tchétchène": "ce",
    "tchouvache": "cv",
    "télougou": "te",
    "temne": "tem",
    "tereno": "ter",
    "tetum": "tet",
    "thaï": "th",
    "thaïes, autres langues": "tai",
    "tibétain": "bo",
    "tigré": "tig",
    "tigrigna": "ti",
    "tiv": "tiv",
    "tlingit": "tli",
    "tok pisin": "tpi",
    "tokelau": "tkl",
    "tonga (Nyasa)": "tog",
    "tongan (Îles Tonga)": "to",
    "touva": "tyv",
    "tsigane": "rom",
    "tsimshian": "tsi",
    "tsonga": "ts",
    "tswana": "tn",
    "tumbuka": "tum",
    "tupi, langues": "tup",
    "turc": "tr",
    "turc ottoman (1500-1928)": "ota",
    "turkmène": "tk",
    "tuvalu": "tvl",
    "twi": "tw",
    "ukrainien": "uk",
    "umbundu": "umb",
    "vaï": "vai",
    "venda": "ve",
    "vietnamien": "vi",
    "volapük": "vo",
    "vote": "vot",
    "wakashennes, langues": "wak",
    "walamo": "wal",
    "wallon": "wa",
    "waray": "war",
    "washo": "was",
    "wolof": "wo",
    "xhosa": "xh",
    "yao": "yao",
    "yapois": "yap",
    "yi de Sichuan": "ii",
    "yiddish": "yi",
    "yoruba": "yo",
    "yupik, langues": "ypk",
    "zandé, langues": "znd",
    "zapotèque": "zap",
    "zaza; dimili; dimli; kirdki; kirmanjki; zazaki": "zza",
    "zenaga": "zen",
    "zhuang; chuang": "za",
    "zoulou": "zu",
    "zuni": "zun"
}

english_to_rfc5646 = {
    "abkhazian": "ab",
    "achinese": "ace",
    "acoli": "ach",
    "adangme": "ada",
    "adyghe; adygei": "ady",
    "afar": "aa",
    "afrihili": "afh",
    "afrikaans": "af",
    "afro-asiatic (other)": "afa",
    "ainu": "ain",
    "akan": "ak",
    "akkadian": "akk",
    "albanian": "sq",
    "swiss german; alemannic": "gsw",
    "aleut": "ale",
    "algonquian languages": "alg",
    "german": "de",
    "german, low; low german; saxon, low; low saxon": "nds",
    "german, middle high (ca.1050-1500)": "gmh",
    "german, old high (ca.750-1050)": "goh",
    "southern altai": "alt",
    "altaic (other)": "tut",
    "central american indian (other)": "cai",
    "amharic": "am",
    "angika": "anp",
    "english": "en",
    "english, middle (1100-1500)": "enm",
    "english, old (ca.450-1100)": "ang",
    "apache languages": "apa",
    "arabic": "ar",
    "aragonese": "an",
    "aramaic": "arc",
    "arapaho": "arp",
    "arawak": "arw",
    "armenian": "hy",
    "aromanian; arumanian; macedo-romanian": "rup",
    "artificial (other)": "art",
    "assamese": "as",
    "asturian; bable": "ast",
    "athapascan languages": "ath",
    "australian languages": "aus",
    "avaric": "av",
    "avestan": "ae",
    "awadhi": "awa",
    "aymara": "ay",
    "azerbaijani": "az",
    "bashkir": "ba",
    "balinese": "ban",
    "baluchi": "bal",
    "baltic (other)": "bat",
    "bambara": "bm",
    "bamileke languages": "bai",
    "banda languages": "bad",
    "bantu (other)": "bnt",
    "lower sorbian": "dsb",
    "basa": "bas",
    "basque": "eu",
    "batak languages": "btk",
    "beja": "bej",
    "bemba": "bem",
    "bengali": "bn",
    "berber (other)": "ber",
    "bhojpuri": "bho",
    "bislama": "bi",
    "belarusian": "be",
    "bihari languages": "bh",
    "bikol": "bik",
    "bini; edo": "bin",
    "burmese": "my",
    "siksika": "bla",
    "blin; bilin": "byn",
    "bosnian": "bs",
    "buriat": "bua",
    "braj": "bra",
    "breton": "br",
    "buginese": "bug",
    "bulgarian": "bg",
    "caddo": "cad",
    "karelian": "krl",
    "catalan; valencian": "ca",
    "caucasian (other)": "cau",
    "cebuano": "ceb",
    "celtic (other)": "cel",
    "chamic languages": "cmc",
    "chamorro": "ch",
    "shan": "shn",
    "cherokee": "chr",
    "cheyenne": "chy",
    "chibcha": "chb",
    "chichewa; chewa; nyanja": "ny",
    "chinese": "zh",
    "chinook jargon": "chn",
    "chipewyan": "chp",
    "choctaw": "cho",
    "chuukese": "chk",
    "coptic": "cop",
    "korean": "ko",
    "cornish": "kw",
    "corsican": "co",
    "cushitic (other)": "cus",
    "cree": "cr",
    "creoles and pidgins, english based (other)": "cpe",
    "creoles and pidgins (other)": "crp",
    "creoles and pidgins, french-based (other)": "cpf",
    "creoles and pidgins, portuguese-based (other)": "cpp",
    "croatian": "hr",
    "dakota": "dak",
    "danish": "da",
    "dargwa": "dar",
    "land dayak languages": "day",
    "delaware": "del",
    "dinka": "din",
    "dyula": "dyu",
    "uncoded languages": "mis",
    "chagatai": "chg",
    "dogri": "doi",
    "dogrib": "dgr",
    "duala": "dua",
    "dravidian (other)": "dra",
    "dzongkha": "dz",
    "scots": "sco",
    "efik": "efi",
    "egyptian (ancient)": "egy",
    "ekajuk": "eka",
    "elamite": "elx",
    "erzya": "myv",
    "slave (athapascan)": "den",
    "spanish; castilian": "es",
    "esperanto": "eo",
    "estonian": "et",
    "ewe": "ee",
    "ewondo": "ewo",
    "fang": "fan",
    "fanti": "fat",
    "faroese": "fo",
    "fijian": "fj",
    "filipino; pilipino": "fil",
    "finno-ugrian (other)": "fiu",
    "finnish": "fi",
    "fon": "fon",
    "french": "fr",
    "french, old (842-ca.1400)": "fro",
    "french, middle (ca.1400-1600)": "frm",
    "friulian": "fur",
    "western frisian": "fy",
    "eastern frisian": "frs",
    "northern frisian": "frr",
    "ga": "gaa",
    "gaelic; scottish gaelic": "gd",
    "galician": "gl",
    "oromo": "om",
    "welsh": "cy",
    "ganda": "lg",
    "gayo": "gay",
    "gbaya": "gba",
    "georgian": "ka",
    "germanic (other)": "gem",
    "gondi": "gon",
    "gorontalo": "gor",
    "gothic": "got",
    "gujarati": "gu",
    "grebo": "grb",
    "greek, ancient (to 1453)": "grc",
    "greek, modern (1453-)": "el",
    "kalaallisut; greenlandic": "kl",
    "guarani": "gn",
    "geez": "gez",
    "gwich´in": "gwi",
    "haida": "hai",
    "haitian; haitian creole": "ht",
    "hausa": "ha",
    "upper sorbian": "hsb",
    "hawaiian": "haw",
    "hebrew": "he",
    "herero": "hz",
    "hiligaynon": "hil",
    "himachali": "him",
    "hindi": "hi",
    "hiri motu": "ho",
    "hittite": "hit",
    "hmong": "hmn",
    "hungarian": "hu",
    "hupa": "hup",
    "yakut": "sah",
    "iban": "iba",
    "ido": "io",
    "igbo": "ig",
    "ijo languages": "ijo",
    "iloko": "ilo",
    "undetermined": "und",
    "north american indian": "nai",
    "south american indian (other)": "sai",
    "indic (other)": "inc",
    "indo-european (other)": "ine",
    "indonesian": "id",
    "ingush": "inh",
    "interlingua (international auxiliary language association)": "ia",
    "interlingue": "ie",
    "inuktitut": "iu",
    "inupiaq": "ik",
    "iranian (other)": "ira",
    "irish": "ga",
    "irish, old (to 900)": "sga",
    "irish, middle (900-1200)": "mga",
    "iroquoian languages": "iro",
    "icelandic": "is",
    "italian": "it",
    "japanese": "ja",
    "javanese": "jv",
    "judeo-arabic": "jrb",
    "ladino": "lad",
    "judeo-persian": "jpr",
    "kabardian": "kbd",
    "kabyle": "kab",
    "kachin; jingpho": "kac",
    "kashubian": "csb",
    "kalmyk; oirat": "xal",
    "kamba": "kam",
    "kannada": "kn",
    "kanuri": "kr",
    "kara-kalpak": "kaa",
    "karachay-balkar": "krc",
    "karen languages": "kar",
    "galibi carib": "car",
    "kashmiri": "ks",
    "kawi": "kaw",
    "kazakh": "kk",
    "khasi": "kha",
    "central khmer": "km",
    "khoisan (other)": "khi",
    "khotanese": "kho",
    "kikuyu; gikuyu": "ki",
    "kimbundu": "kmb",
    "kirghiz; kyrgyz": "ky",
    "gilbertese": "gil",
    "klingon; tlhingan-hol": "tlh",
    "komi": "kv",
    "kongo": "kg",
    "konkani": "kok",
    "kosraean": "kos",
    "kumyk": "kum",
    "kpelle": "kpe",
    "kru languages": "kro",
    "kuanyama; kwanyama": "kj",
    "kurdish": "ku",
    "kurukh": "kru",
    "kutenai": "kut",
    "lahnda": "lah",
    "lamba": "lam",
    "sign languages": "sgn",
    "lao": "lo",
    "latin": "la",
    "latvian": "lv",
    "lezghian": "lez",
    "limburgan; limburger; limburgish": "li",
    "lingala": "ln",
    "lithuanian": "lt",
    "lojban": "jbo",
    "lozi": "loz",
    "luba-katanga": "lu",
    "luba-lulua": "lua",
    "luiseno": "lui",
    "lunda": "lun",
    "luo (kenya and tanzania)": "luo",
    "lushai": "lus",
    "luxembourgish; letzeburgesch": "lb",
    "macedonian": "mk",
    "madurese": "mad",
    "magahi": "mag",
    "maithili": "mai",
    "makasar": "mak",
    "malay": "ms",
    "malayalam": "ml",
    "austronesian (other)": "map",
    "divehi; dhivehi; maldivian": "dv",
    "malagasy": "mg",
    "maltese": "mt",
    "mandar": "mdr",
    "manchu": "mnc",
    "mandingo": "man",
    "manipuri": "mni",
    "manobo languages": "mno",
    "manx": "gv",
    "maori": "mi",
    "mapudungun; mapuche": "arn",
    "marathi": "mr",
    "mari": "chm",
    "marshallese": "mh",
    "marwari": "mwr",
    "masai": "mas",
    "mayan languages": "myn",
    "mende": "men",
    "mi'kmaq; micmac": "mic",
    "minangkabau": "min",
    "mirandese": "mwl",
    "mohawk": "moh",
    "moksha": "mdf",
    "mon-khmer (other)": "mkh",
    "mongo": "lol",
    "mongolian": "mn",
    "mossi": "mos",
    "munda languages": "mun",
    "multiple languages": "mul",
    "creek": "mus",
    "n'ko": "nqo",
    "nahuatl languages": "nah",
    "neapolitan": "nap",
    "nauru": "na",
    "navajo; navaho": "nv",
    "ndebele, north; north ndebele": "nd",
    "ndebele, south; south ndebele": "nr",
    "ndonga": "ng",
    "dutch, middle (ca.1050-1350)": "dum",
    "dutch; flemish": "nl",
    "nepal bhasa; newari": "new",
    "nepali": "ne",
    "classical newari; old newari; classical nepal bhasa": "nwc",
    "nias": "nia",
    "niger-kordofanian (other)": "nic",
    "nilo-saharan (other)": "ssa",
    "niuean": "niu",
    "nogai": "nog",
    "norse, old": "non",
    "norwegian": "no",
    "norwegian bokmål; bokmål, norwegian;": "nb",
    "norwegian nynorsk; nynorsk, norwegian": "nn",
    "nubian languages": "nub",
    "nyamwezi": "nym",
    "nyankole": "nyn",
    "nyoro": "nyo",
    "nzima": "nzi",
    "occitan (post 1500); provençal": "oc",
    "ojibwa": "oj",
    "oriya": "or",
    "osage": "osa",
    "ossetian; ossetic": "os",
    "otomian languages": "oto",
    "udmurt": "udm",
    "ugaritic": "uga",
    "uighur; uyghur": "ug",
    "urdu": "ur",
    "uzbek": "uz",
    "pushto": "ps",
    "pahlavi": "pal",
    "palauan": "pau",
    "pali": "pi",
    "pampanga": "pam",
    "pangasinan": "pag",
    "papiamento": "pap",
    "papuan (other)": "paa",
    "no linguistic content": "zxx",
    "pedi; sepedi; northern sotho": "nso",
    "panjabi; punjabi": "pa",
    "persian": "fa",
    "persian, old (ca.600-400 b.c.)": "peo",
    "fulah": "ff",
    "phoenician": "phn",
    "philippine (other)": "phi",
    "pohnpeian": "pon",
    "polish": "pl",
    "portuguese": "pt",
    "prakrit languages": "pra",
    "provençal, old (to 1500)": "pro",
    "quechua": "qu",
    "rajasthani": "raj",
    "rapanui": "rap",
    "rarotongan; cook islands maori": "rar",
    "reserved for local use": "qaa..qtz",
    "romansh": "rm",
    "romance (other)": "roa",
    "romanian": "ro",
    "rundi": "rn",
    "russian": "ru",
    "kinyarwanda": "rw",
    "salishan languages": "sal",
    "samaritan aramaic": "sam",
    "inari sami": "smn",
    "lule sami": "smj",
    "northern sami": "se",
    "southern sami": "sma",
    "skolt sami": "sms",
    "sami languages (other)": "smi",
    "samoan": "sm",
    "sandawe": "sad",
    "sango": "sg",
    "sanskrit": "sa",
    "santali": "sat",
    "sardinian": "sc",
    "sasak": "sas",
    "selkup": "sel",
    "semitic (other)": "sem",
    "serbian": "sr",
    "serer": "srr",
    "shona": "sn",
    "sicilian": "scn",
    "sidamo": "sid",
    "sindhi": "sd",
    "sinhala; sinhalese": "si",
    "sino-tibetan (other)": "sit",
    "siouan languages": "sio",
    "slavic languages": "sla",
    "church slavic; old slavonic; church slavonic; old bulgarian; old church slavonic": "cu",
    "slovak": "sk",
    "slovenian": "sl",
    "sogdian": "sog",
    "somali": "so",
    "songhai languages": "son",
    "soninke": "snk",
    "sorbian languages": "wen",
    "sotho, southern": "st",
    "sundanese": "su",
    "susu": "sus",
    "sranan tongo": "srn",
    "swedish": "sv",
    "sukuma": "suk",
    "sumerian": "sux",
    "swahili": "sw",
    "swati": "ss",
    "blissymbols": "zbl",
    "syriac": "syr",
    "classical syriac": "syc",
    "tajik": "tg",
    "tagalog": "tl",
    "tahitian": "ty",
    "tamashek": "tmh",
    "tamil": "ta",
    "tatar": "tt",
    "crimean tatar; crimean turkish": "crh",
    "czech": "cs",
    "chechen": "ce",
    "chuvash": "cv",
    "telugu": "te",
    "timne": "tem",
    "tereno": "ter",
    "tetum": "tet",
    "thai": "th",
    "tai (other)": "tai",
    "tibetan": "bo",
    "tigre": "tig",
    "tigrinya": "ti",
    "tiv": "tiv",
    "tlingit": "tli",
    "tok pisin": "tpi",
    "tokelau": "tkl",
    "tonga (nyasa)": "tog",
    "tonga (tonga islands)": "to",
    "tuvinian": "tyv",
    "romany": "rom",
    "tsimshian": "tsi",
    "tsonga": "ts",
    "tswana": "tn",
    "tumbuka": "tum",
    "tupi languages": "tup",
    "turkish": "tr",
    "turkish, ottoman (1500-1928)": "ota",
    "turkmen": "tk",
    "tuvalu": "tvl",
    "twi": "tw",
    "ukrainian": "uk",
    "umbundu": "umb",
    "vai": "vai",
    "venda": "ve",
    "vietnamese": "vi",
    "volapük": "vo",
    "votic": "vot",
    "wakashan languages": "wak",
    "walamo": "wal",
    "walloon": "wa",
    "waray": "war",
    "washo": "was",
    "wolof": "wo",
    "xhosa": "xh",
    "yao": "yao",
    "yapese": "yap",
    "sichuan yi": "ii",
    "yiddish": "yi",
    "yoruba": "yo",
    "yupik languages": "ypk",
    "zande languages": "znd",
    "zapotec": "zap",
    "zaza; dimili; dimli; kirdki; kirmanjki; zazaki": "zza",
    "zenaga": "zen",
    "zhuang; chuang": "za",
    "zulu": "zu",
    "zuni": "zun"
}


def find_language_authority(language):
    """ Return the language authority:
        - iso639-1
        - iso639-2b
        - iso639-2t
        - iso639-3
        - rfc5646
    """
    if language:
        language = language.lower()
        minus_index = language.find("-")
        if len(language) == 2 and language in iso639_1_to_iso639_2b:
            return "iso639-1"
        elif minus_index == 2 and language[:2] in iso639_1_to_iso639_2b:
            return "rfc5646"
        elif len(language) == 3 and language in iso639_2b_to_rfc5646:
            return "iso639-2b"
        elif len(language) == 3 and language in iso639_2t_to_rfc5646:
            return "iso639-2t"
        elif minus_index == 3 and language[:3] in iso639_2t_to_rfc5646:
            return "rfc5646"
        else:
            logging.error("Fixme ! Unknown language authority for language code: {}".format(language))
    return None


def extract_rfc5646_language(rfc5646):
    # RFC5646 langtag =
    #                   language
    #                   ["-" script]
    #                   ["-" region]
    #                   *("-" variant)
    #                   *("-" extension)
    #                   ["-" privateuse]
    # 
    # Example:
    # - "fr" (French)
    # - "de-AT" (German as used in Austria)
    # - "zh-Hant" (Chinese written using the Traditional Chinese script)
    # - "zh-Hans" (Chinese written using the Simplified Chinese script)
    # - "zh-yue-HK" (Chinese, Cantonese, as used in Hong Kong SAR)
    # - "sr-Latn-RS" (Serbian written using Latin script as used in Serbia ('RS').
    # - "es-419" (Spanish appropriate to the UN-defined Latin America and Caribbean region ('419'))
    # - "en-scotland-fonipa" (English, Scottish dialect, IPA phonetic transcription)
    # - "sl-rozaj-biske" (San Giorgio dialect of Resian dialect of Slovenian)
    # - "hy-Latn-IT-arevela" (Eastern Armenian written in Latin script, as used in Italy)
    # 
    # 
    #  language      = 2*3ALPHA            ; shortest ISO 639 code
    #                  ["-" extlang]       ; sometimes followed by
    #                                      ; extended language subtags
    #                / 4ALPHA              ; or reserved for future use
    #                / 5*8ALPHA            ; or registered language subtag
    # 
    #  extlang       = 3ALPHA              ; selected ISO 639 codes
    #                  *2("-" 3ALPHA)      ; permanently reserved
    # 
    #  script        = 4ALPHA              ; ISO 15924 code
    # 
    #  region        = 2ALPHA              ; ISO 3166-1 code
    #                / 3DIGIT              ; UN M.49 code
    # 
    #  variant       = 5*8alphanum         ; registered variants
    #                / (DIGIT 3alphanum)
    # 
    #  extension     = singleton 1*("-" (2*8alphanum))
    # 
    #                                      ; Single alphanumerics
    #                                      ; "x" reserved for private use
    #  singleton     = DIGIT               ; 0 - 9
    #                / %x41-57             ; A - W
    #                / %x59-5A             ; Y - Z
    #                / %x61-77             ; a - w
    #                / %x79-7A             ; y - z
    # 
    #  privateuse    = "x" 1*("-" (1*8alphanum))
    # 
    #  grandfathered = irregular           ; non-redundant tags registered
    #                / regular             ; during the RFC 5646 era
    # 
    #  irregular     = "en-GB-oed"         ; irregular tags do not match
    #                / "i-ami"             ; the 'langtag' production and
    #                / "i-bnn"             ; would not otherwise be
    #                / "i-default"         ; considered 'well-formed'
    #                / "i-enochian"        ; These tags are all valid,
    #                / "i-hak"             ; but most are deprecated
    #                / "i-klingon"         ; in favor of more modern
    #                / "i-lux"             ; subtags or subtag
    #                / "i-mingo"           ; combination
    #                / "i-navajo"
    #                / "i-pwn"
    #                / "i-tao"
    #                / "i-tay"
    #                / "i-tsu"
    #                / "sgn-BE-FR"
    #                / "sgn-BE-NL"
    #                / "sgn-CH-DE"
    # 
    #  regular       = "art-lojban"        ; these tags match the 'langtag'
    #                / "cel-gaulish"       ; production, but their subtags
    #                / "no-bok"            ; are not extended language
    #                / "no-nyn"            ; or variant subtags: their meaning
    #                / "zh-guoyu"          ; is defined by their registration
    #                / "zh-hakka"          ; and all of these are deprecated
    #                / "zh-min"            ; in favor of a more modern
    #                / "zh-min-nan"        ; subtag or sequence of subtags
    #                / "zh-xiang"
    # 
    #  alphanum      = (ALPHA / DIGIT)     ; letters and numbers
    # 
    # Simplified RFC5646 formats managed by this function:
    # "i-" <iana_registered_code>
    # "x-" <private_use_code>
    # <iso_639_1_code>
    # <iso_639_2_code>
    # <iso_639_1or2_code> "-" <iso_3166_code>
    # <iso_639_1or2_code> "-" <iso_15924_code>
    # <iso_639_1or2_code> "-" <iso_15924_code> "-" <iso_3166_code>

    if rfc5646:
        rfc5646 = rfc5646.lower()
        first_minus_index = rfc5646.find("-")

        if first_minus_index == 3 or len(rfc5646) == 3:
            lang = rfc5646[:3]
            if lang in iso639_2b_to_rfc5646:
                # iso639-2b ?
                result = iso639_2b_to_rfc5646[lang]
                if result:
                    return result
            if lang in iso639_2t_to_rfc5646:
                # iso639-2t ?
                result = iso639_2t_to_rfc5646[lang]
                if result:
                    return result
            else:
                logging.error("Fixme ! Unknown language format, not an iso639-2b or iso639-2t: {}".format(rfc5646))

        elif first_minus_index == 2 or len(rfc5646) == 2:
            lang = rfc5646[:2]
            if lang in iso639_1_to_iso639_2b:
                # iso639-1 ?
                return lang
            else:
                logging.error("Fixme ! Unknown language format, not an iso639-1: {}".format(rfc5646))

        elif first_minus_index == 1:
            first_char = rfc5646[:1]
            if first_char == "i":
                # iana_registered_code
                logging.error("Fixme ! iana_registered_code is not managed for rfc5646: {}".format(rfc5646))
            elif first_char == "x":
                # private_use_code
                logging.error("Fixme ! private_use_code is not managed for rfc5646: {}".format(rfc5646))
            else:
                # unknown
                logging.error("Fixme ! Unknown prefix code for rfc5646: {}".format(rfc5646))

        else:
            logging.error("Fixme ! Unknown language format for rfc5646: {}".format(rfc5646))


def convert_iso639_1_to_iso639_2b(iso639_1):
    if iso639_1:
        iso639_1 = iso639_1.lower()
        if iso639_1 in iso639_1_to_iso639_2b:
            return iso639_1_to_iso639_2b[iso639_1]


def convert_iso639_1_to_rfc5646(iso639_1):
    if iso639_1:
        iso639_1 = iso639_1.lower()
        if iso639_1 in iso639_1_to_iso639_2b: 
            return iso639_1


def convert_iso639_2b_to_iso639_1(iso639_2b):
    if iso639_2b:
        iso639_2b = iso639_2b.lower()
        if iso639_2b in iso639_2b_to_iso639_1:
            return iso639_2b_to_iso639_1[iso639_2b]
        else:
            return iso639_2b


def convert_iso639_2b_to_rfc5646(iso639_2b):
    if iso639_2b:
        iso639_2b = iso639_2b.lower()
        if iso639_2b in iso639_2b_to_rfc5646:
            return iso639_2b_to_rfc5646[iso639_2b]


def convert_iso639_2t_to_rfc5646(iso639_2t):
    if iso639_2t:
        iso639_2t = iso639_2t.lower()
        if iso639_2t in iso639_2t_to_rfc5646:
            return iso639_2t_to_rfc5646[iso639_2t]


def convert_english_to_rfc5646(english):
    if english:
        english = english.lower()
        if english in english_to_rfc5646:
            return english_to_rfc5646[english]


def convert_french_to_rfc5646(french):
    if french:
        french = french.lower()
        if french in french_to_rfc5646:
            return french_to_rfc5646[french]


def convert_rfc5646_to_iso639_2b(rfc5646):
    if rfc5646:
        rfc5646 = extract_rfc5646_language(rfc5646)
        if len(rfc5646) == 2:
            # iso639-1
            return convert_iso639_1_to_iso639_2b(rfc5646)
        elif len(rfc5646) == 3:
            if rfc5646 in iso639_2b_to_rfc5646:
                # iso639-2b
                return rfc5646
            elif rfc5646 in iso639_2t_to_iso639_2b:
                # iso639-2t
                return iso639_2t_to_iso639_2b[rfc5646]


def convert_unknown_format_to_rfc5646(unknown):
    if unknown:
        unknown = unknown.lower()
        result = None
        if unknown in iso639_1_to_iso639_2b:
            result = unknown
        elif unknown in iso639_2b_to_rfc5646:
            result = iso639_2b_to_rfc5646[unknown]
        elif unknown in iso639_2t_to_rfc5646:
            result = iso639_2t_to_rfc5646[unknown]
        elif unknown in english_to_rfc5646:
            result = english_to_rfc5646[unknown]
        elif unknown in french_to_rfc5646:
            result = french_to_rfc5646[unknown]
        else:
            result = extract_rfc5646_language(unknown)
        if result:
            return result
        else:
            logging.warning("Fixme ! Unrecognize language term: {}".format(unknown))


def test():
    logging.debug(find_language_authority("fre"))
    logging.debug(extract_rfc5646_language("fr-FR"))
    logging.debug(convert_iso639_1_to_iso639_2b("fr"))
    logging.debug(convert_iso639_1_to_rfc5646("fr"))
    logging.debug(convert_iso639_2b_to_iso639_1("fre"))
    logging.debug(convert_iso639_2b_to_rfc5646("fre"))
    logging.debug(convert_iso639_2t_to_rfc5646("fra"))
    logging.debug(convert_english_to_rfc5646("french"))
    logging.debug(convert_french_to_rfc5646("français"))
    logging.debug(convert_rfc5646_to_iso639_2b("fr-FR"))
    logging.debug(convert_unknown_format_to_rfc5646("fr-FR"))

#test()
