#!/usr/bin/python
# -*- coding: utf-8 -*-
# coding=utf-8

iso639_1_to_iso639_2 = {
    "aa" : "aar",
    "ab" : "abk",
    "ae" : "ave",
    "af" : "afr",
    "ak" : "aka",
    "am" : "amh",
    "an" : "arg",
    "ar" : "ara",
    "as" : "asm",
    "av" : "ava",
    "ay" : "aym",
    "az" : "aze",
    "ba" : "bak",
    "be" : "bel",
    "bg" : "bul",
    "bh" : "bih",
    "bi" : "bis",
    "bm" : "bam",
    "bn" : "ben",
    "bo" : "tib",
    "br" : "bre",
    "bs" : "bos",
    "ca" : "cat",
    "ce" : "che",
    "ch" : "cha",
    "co" : "cos",
    "cr" : "cre",
    "cs" : "cze",
    "cu" : "chu",
    "cv" : "chv",
    "cy" : "wel",
    "da" : "dan",
    "de" : "ger",
    "dv" : "div",
    "dz" : "dzo",
    "ee" : "ewe",
    "el" : "gre",
    "en" : "eng",
    "eo" : "epo",
    "es" : "spa",
    "et" : "est",
    "eu" : "baq",
    "fa" : "per",
    "ff" : "ful",
    "fi" : "fin",
    "fj" : "fij",
    "fo" : "fao",
    "fr" : "fre",
    "fy" : "fry",
    "ga" : "gle",
    "gd" : "gla",
    "gl" : "glg",
    "gn" : "grn",
    "gu" : "guj",
    "gv" : "glv",
    "ha" : "hau",
    "he" : "heb",
    "hi" : "hin",
    "ho" : "hmo",
    "hr" : "scr",
    "ht" : "hat",
    "hu" : "hun",
    "hy" : "arm",
    "hz" : "her",
    "ia" : "ina",
    "id" : "ind",
    "ie" : "ile",
    "ig" : "ibo",
    "ii" : "iii",
    "ik" : "ipk",
    "io" : "ido",
    "is" : "ice",
    "it" : "ita",
    "iu" : "iku",
    "ja" : "jpn",
    "jv" : "jav",
    "ka" : "geo",
    "kg" : "kon",
    "ki" : "kik",
    "kj" : "kua",
    "kk" : "kaz",
    "kl" : "kal",
    "km" : "khm",
    "kn" : "kan",
    "ko" : "kor",
    "kr" : "kau",
    "ks" : "kas",
    "ku" : "kur",
    "kv" : "kom",
    "kw" : "cor",
    "ky" : "kir",
    "la" : "lat",
    "lb" : "ltz",
    "lg" : "lug",
    "li" : "lim",
    "ln" : "lin",
    "lo" : "lao",
    "lt" : "lit",
    "lu" : "lub",
    "lv" : "lav",
    "mg" : "mlg",
    "mh" : "mah",
    "mi" : "mao",
    "mk" : "mac",
    "ml" : "mal",
    "mn" : "mon",
    "mo" : "mol",
    "mr" : "mar",
    "ms" : "may",
    "mt" : "mlt",
    "my" : "bur",
    "na" : "nau",
    "nb" : "nob",
    "nd" : "nde",
    "ne" : "nep",
    "ng" : "ndo",
    "nl" : "dut",
    "nn" : "nno",
    "no" : "nor",
    "nr" : "nbl",
    "nv" : "nav",
    "ny" : "nya",
    "oc" : "oci",
    "oj" : "oji",
    "om" : "orm",
    "or" : "ori",
    "os" : "oss",
    "pa" : "pan",
    "pi" : "pli",
    "pl" : "pol",
    "ps" : "pus",
    "pt" : "por",
    "qu" : "que",
    "rm" : "roh",
    "rn" : "run",
    "ro" : "rum",
    "ru" : "rus",
    "rw" : "kin",
    "sa" : "san",
    "sc" : "srd",
    "sd" : "snd",
    "se" : "sme",
    "sg" : "sag",
    "si" : "sin",
    "sk" : "slo",
    "sl" : "slv",
    "sm" : "smo",
    "sn" : "sna",
    "so" : "som",
    "sq" : "alb",
    "sr" : "scc",
    "ss" : "ssw",
    "st" : "sot",
    "su" : "sun",
    "sv" : "swe",
    "sw" : "swa",
    "ta" : "tam",
    "te" : "tel",
    "tg" : "tgk",
    "th" : "tha",
    "ti" : "tir",
    "tk" : "tuk",
    "tl" : "tgl",
    "tn" : "tsn",
    "to" : "ton",
    "tr" : "tur",
    "ts" : "tso",
    "tt" : "tat",
    "tw" : "twi",
    "ty" : "tah",
    "ug" : "uig",
    "uk" : "ukr",
    "ur" : "urd",
    "uz" : "uzb",
    "ve" : "ven",
    "vi" : "vie",
    "vo" : "vol",
    "wa" : "wln",
    "wo" : "wol",
    "xh" : "xho",
    "yi" : "yid",
    "yo" : "yor",
    "za" : "zha",
    "zh" : "chi",
    "zu" : "zul"
}

iso639_2_to_iso639_1 = {
    "aar" : "aa",
    "abk" : "ab",
    "ace" : None,
    "ach" : None,
    "ada" : None,
    "ady" : None,
    "afa" : None,
    "afh" : None,
    "afr" : "af",
    "ain" : None,
    "aka" : "ak",
    "akk" : None,
    "alb" : "sq",
    "ale" : None,
    "alg" : None,
    "alt" : None,
    "amh" : "am",
    "ang" : None,
    "anp" : None,
    "apa" : None,
    "ara" : "ar",
    "arc" : None,
    "arg" : "an",
    "arm" : "hy",
    "arn" : None,
    "arp" : None,
    "art" : None,
    "arw" : None,
    "asm" : "as",
    "ast" : None,
    "ath" : None,
    "aus" : None,
    "ava" : "av",
    "ave" : "ae",
    "awa" : None,
    "aym" : "ay",
    "aze" : "az",
    "bad" : None,
    "bai" : None,
    "bak" : "ba",
    "bal" : None,
    "bam" : "bm",
    "ban" : None,
    "baq" : "eu",
    "bas" : None,
    "bat" : None,
    "bej" : None,
    "bel" : "be",
    "bem" : None,
    "ben" : "bn",
    "ber" : None,
    "bho" : None,
    "bih" : "bh",
    "bik" : None,
    "bin" : None,
    "bis" : "bi",
    "bla" : None,
    "bnt" : None,
    "bod" : "bo",
    "bos" : "bs",
    "bra" : None,
    "bre" : "br",
    "btk" : None,
    "bua" : None,
    "bug" : None,
    "bul" : "bg",
    "bur" : "my",
    "byn" : None,
    "cad" : None,
    "cai" : None,
    "car" : None,
    "cat" : "ca",
    "cau" : None,
    "ceb" : None,
    "cel" : None,
    "ces" : "cs",
    "cha" : "ch",
    "chb" : None,
    "che" : "ce",
    "chg" : None,
    "chi" : "zh",
    "chk" : None,
    "chm" : None,
    "chn" : None,
    "cho" : None,
    "chp" : None,
    "chr" : None,
    "chu" : "cu",
    "chv" : "cv",
    "chy" : None,
    "cmc" : None,
    "cop" : None,
    "cor" : "kw",
    "cos" : "co",
    "cpe" : None,
    "cpf" : None,
    "cpp" : None,
    "cre" : "cr",
    "crh" : None,
    "crp" : None,
    "csb" : None,
    "cus" : None,
    "cym" : "cy",
    "cze" : "cs",
    "dak" : None,
    "dan" : "da",
    "dar" : None,
    "day" : None,
    "del" : None,
    "den" : None,
    "deu" : "de",
    "dgr" : None,
    "din" : None,
    "div" : "dv",
    "doi" : None,
    "dra" : None,
    "dsb" : None,
    "dua" : None,
    "dum" : None,
    "dut" : "nl",
    "dyu" : None,
    "dzo" : "dz",
    "efi" : None,
    "egy" : None,
    "eka" : None,
    "ell" : "el",
    "elx" : None,
    "eng" : "en",
    "enm" : None,
    "epo" : "eo",
    "est" : "et",
    "eus" : "eu",
    "ewe" : "ee",
    "ewo" : None,
    "fan" : None,
    "fao" : "fo",
    "fas" : "fa",
    "fat" : None,
    "fij" : "fj",
    "fil" : None,
    "fin" : "fi",
    "fiu" : None,
    "fon" : None,
    "fra" : "fr",
    "fre" : "fr",
    "frm" : None,
    "fro" : None,
    "frr" : None,
    "frs" : None,
    "fry" : "fy",
    "ful" : "ff",
    "fur" : None,
    "gaa" : None,
    "gay" : None,
    "gba" : None,
    "gem" : None,
    "geo" : "ka",
    "ger" : "de",
    "gez" : None,
    "gil" : None,
    "gla" : "gd",
    "gle" : "ga",
    "glg" : "gl",
    "glv" : "gv",
    "gmh" : None,
    "goh" : None,
    "gon" : None,
    "gor" : None,
    "got" : None,
    "grb" : None,
    "grc" : None,
    "gre" : "el",
    "grn" : "gn",
    "gsw" : None,
    "guj" : "gu",
    "gwi" : None,
    "hai" : None,
    "hat" : "ht",
    "hau" : "ha",
    "haw" : None,
    "heb" : "he",
    "her" : "hz",
    "hil" : None,
    "him" : None,
    "hin" : "hi",
    "hit" : None,
    "hmn" : None,
    "hmo" : "ho",
    "hrv" : "hr",
    "hsb" : None,
    "hun" : "hu",
    "hup" : None,
    "hye" : "hy",
    "iba" : None,
    "ibo" : "ig",
    "ice" : "is",
    "ido" : "io",
    "iii" : "ii",
    "ijo" : None,
    "iku" : "iu",
    "ile" : "ie",
    "ilo" : None,
    "ina" : "ia",
    "inc" : None,
    "ind" : "id",
    "ine" : None,
    "inh" : None,
    "ipk" : "ik",
    "ira" : None,
    "iro" : None,
    "isl" : "is",
    "ita" : "it",
    "jav" : "jv",
    "jbo" : None,
    "jpn" : "ja",
    "jpr" : None,
    "jrb" : None,
    "kaa" : None,
    "kab" : None,
    "kac" : None,
    "kal" : "kl",
    "kam" : None,
    "kan" : "kn",
    "kar" : None,
    "kas" : "ks",
    "kat" : "ka",
    "kau" : "kr",
    "kaw" : None,
    "kaz" : "kk",
    "kbd" : None,
    "kha" : None,
    "khi" : None,
    "khm" : "km",
    "kho" : None,
    "kik" : "ki",
    "kin" : "rw",
    "kir" : "ky",
    "kmb" : None,
    "kok" : None,
    "kom" : "kv",
    "kon" : "kg",
    "kor" : "ko",
    "kos" : None,
    "kpe" : None,
    "krc" : None,
    "kro" : None,
    "kru" : None,
    "kua" : "kj",
    "kum" : None,
    "kur" : "ku",
    "kut" : None,
    "lad" : None,
    "lah" : None,
    "lam" : None,
    "lao" : "lo",
    "lat" : "la",
    "lav" : "lv",
    "lez" : None,
    "lim" : "li",
    "lin" : "ln",
    "lit" : "lt",
    "lol" : None,
    "loz" : None,
    "ltz" : "lb",
    "lua" : None,
    "lub" : "lu",
    "lug" : "lg",
    "lui" : None,
    "lun" : None,
    "luo" : None,
    "lus" : None,
    "mac" : "mk",
    "mad" : None,
    "mag" : None,
    "mah" : "mh",
    "mai" : None,
    "mak" : None,
    "mal" : "ml",
    "man" : None,
    "mao" : "mi",
    "map" : None,
    "mar" : "mr",
    "mas" : None,
    "may" : "ms",
    "mdf" : None,
    "mdr" : None,
    "men" : None,
    "mga" : None,
    "mic" : None,
    "min" : None,
    "mis" : None,
    "mkd" : "mk",
    "mkh" : None,
    "mlg" : "mg",
    "mlt" : "mt",
    "mnc" : None,
    "mni" : None,
    "mno" : None,
    "moh" : None,
    "mol" : "mo",
    "mon" : "mn",
    "mos" : None,
    "mri" : "mi",
    "msa" : "ms",
    "mul" : None,
    "mun" : None,
    "mus" : None,
    "mwl" : None,
    "mwr" : None,
    "mya" : "my",
    "myn" : None,
    "myv" : None,
    "nah" : None,
    "nai" : None,
    "nap" : None,
    "nau" : "na",
    "nav" : "nv",
    "nbl" : "nr",
    "nde" : "nd",
    "ndo" : "ng",
    "nds" : None,
    "nep" : "ne",
    "new" : None,
    "nia" : None,
    "nic" : None,
    "niu" : None,
    "nld" : "nl",
    "nno" : "nn",
    "nob" : "nb",
    "nog" : None,
    "non" : None,
    "nor" : "no",
    "nqo" : None,
    "nso" : None,
    "nub" : None,
    "nwc" : None,
    "nya" : "ny",
    "nym" : None,
    "nyn" : None,
    "nyo" : None,
    "nzi" : None,
    "oci" : "oc",
    "oji" : "oj",
    "ori" : "or",
    "orm" : "om",
    "osa" : None,
    "oss" : "os",
    "ota" : None,
    "oto" : None,
    "paa" : None,
    "pag" : None,
    "pal" : None,
    "pam" : None,
    "pan" : "pa",
    "pap" : None,
    "pau" : None,
    "peo" : None,
    "per" : "fa",
    "phi" : None,
    "phn" : None,
    "pli" : "pi",
    "pol" : "pl",
    "pon" : None,
    "por" : "pt",
    "pra" : None,
    "pro" : None,
    "pus" : "ps",
    "qaa" : None,
    "qtz" : None,
    "que" : "qu",
    "raj" : None,
    "rap" : None,
    "rar" : None,
    "roa" : None,
    "roh" : "rm",
    "rom" : None,
    "ron" : "ro",
    "rum" : "ro",
    "run" : "rn",
    "rup" : None,
    "rus" : "ru",
    "sad" : None,
    "sag" : "sg",
    "sah" : None,
    "sai" : None,
    "sal" : None,
    "sam" : None,
    "san" : "sa",
    "sas" : None,
    "sat" : None,
    "scc" : "sr",
    "scn" : None,
    "sco" : None,
    "scr" : "hr",
    "sel" : None,
    "sem" : None,
    "sga" : None,
    "sgn" : None,
    "shn" : None,
    "sid" : None,
    "sin" : "si",
    "sio" : None,
    "sit" : None,
    "sla" : None,
    "slk" : "sk",
    "slo" : "sk",
    "slv" : "sl",
    "sma" : None,
    "sme" : "se",
    "smi" : None,
    "smj" : None,
    "smn" : None,
    "smo" : "sm",
    "sms" : None,
    "sna" : "sn",
    "snd" : "sd",
    "snk" : None,
    "sog" : None,
    "som" : "so",
    "son" : None,
    "sot" : "st",
    "spa" : "es",
    "sqi" : "sq",
    "srd" : "sc",
    "srn" : None,
    "srp" : "sr",
    "srr" : None,
    "ssa" : None,
    "ssw" : "ss",
    "suk" : None,
    "sun" : "su",
    "sus" : None,
    "sux" : None,
    "swa" : "sw",
    "swe" : "sv",
    "syr" : None,
    "tah" : "ty",
    "tai" : None,
    "tam" : "ta",
    "tat" : "tt",
    "tel" : "te",
    "tem" : None,
    "ter" : None,
    "tet" : None,
    "tgk" : "tg",
    "tgl" : "tl",
    "tha" : "th",
    "tib" : "bo",
    "tig" : None,
    "tir" : "ti",
    "tiv" : None,
    "tkl" : None,
    "tlh" : None,
    "tli" : None,
    "tmh" : None,
    "tog" : None,
    "ton" : "to",
    "tpi" : None,
    "tsi" : None,
    "tsn" : "tn",
    "tso" : "ts",
    "tuk" : "tk",
    "tum" : None,
    "tup" : None,
    "tur" : "tr",
    "tut" : None,
    "tvl" : None,
    "twi" : "tw",
    "tyv" : None,
    "udm" : None,
    "uga" : None,
    "uig" : "ug",
    "ukr" : "uk",
    "umb" : None,
    "und" : None,
    "urd" : "ur",
    "uzb" : "uz",
    "vai" : None,
    "ven" : "ve",
    "vie" : "vi",
    "vol" : "vo",
    "vot" : None,
    "wak" : None,
    "wal" : None,
    "war" : None,
    "was" : None,
    "wel" : "cy",
    "wen" : None,
    "wln" : "wa",
    "wol" : "wo",
    "xal" : None,
    "xho" : "xh",
    "yao" : None,
    "yap" : None,
    "yid" : "yi",
    "yor" : "yo",
    "ypk" : None,
    "zap" : None,
    "zen" : None,
    "zha" : "za",
    "zho" : "zh",
    "znd" : None,
    "zul" : "zu",
    "zun" : None,
    "zxx" : None,
    "zza" : None
}

french_to_iso639_2 = {
    "abkhaze" : "abk",
    "aceh" : "ace",
    "acoli" : "ach",
    "adangme" : "ada",
    "adyghé" : "ady",
    "afar" : "aar",
    "afrihili" : "afh",
    "afrikaans" : "afr",
    "afro-asiatiques, autres langues" : "afa",
    "akan" : "aka",
    "akkadien" : "akk",
    "albanais" : "alb",
    "algonquines, langues" : "alg",
    "allemand" : "ger",
    "allemand, bas" : "nds",
    "allemand, moyen haut (ca. 1050-1500)" : "gmh",
    "allemand, vieux haut (ca. 750-1050)" : "goh",
    "altai du sud" : "alt",
    "altaïques, autres langues" : "tut",
    "alémanique" : "gsw",
    "aléoute" : "ale",
    "amharique" : "amh",
    "angika" : "anp",
    "anglais" : "eng",
    "anglais moyen (1100-1500)" : "enm",
    "anglo-saxon (ca.450-1100)" : "ang",
    "apache" : "apa",
    "arabe" : "ara",
    "aragonais" : "arg",
    "araméen" : "arc",
    "arapaho" : "arp",
    "arawak" : "arw",
    "arménien" : "arm",
    "aroumain" : "rup",
    "artificielles, autres langues" : "art",
    "assamais" : "asm",
    "asturien" : "ast",
    "athapascanes, langues" : "ath",
    "australiennes, langues" : "aus",
    "avar" : "ava",
    "avestique" : "ave",
    "awadhi" : "awa",
    "aymara" : "aym",
    "azéri" : "aze",
    "aïnou" : "ain",
    "bable" : "ast",
    "bachkir" : "bak",
    "balinais" : "ban",
    "baloutchi" : "bal",
    "baltiques, autres langues" : "bat",
    "bambara" : "bam",
    "bamilékés, langues" : "bai",
    "banda, langues" : "bad",
    "bantoues, autres langues" : "bnt",
    "bas allemand" : "nds",
    "bas saxon" : "nds",
    "bas-sorabe" : "dsb",
    "basa" : "bas",
    "basque" : "baq",
    "batak, langues" : "btk",
    "bedja" : "bej",
    "bemba" : "bem",
    "bengali" : "ben",
    "berbères, autres langues" : "ber",
    "bhojpuri" : "bho",
    "bichlamar" : "bis",
    "bihari" : "bih",
    "bikol" : "bik",
    "bilen" : "byn",
    "bini" : "bin",
    "birman" : "bur",
    "biélorusse" : "bel",
    "blackfoot" : "bla",
    "blin" : "byn",
    "bosniaque" : "bos",
    "bouriate" : "bua",
    "braj" : "bra",
    "breton" : "bre",
    "bugi" : "bug",
    "bulgare" : "bul",
    "caddo" : "cad",
    "carib" : "car",
    "castillan" : "spa",
    "catalan" : "cat",
    "caucasiennes, autres langues" : "cau",
    "cebuano" : "ceb",
    "celtiques, autres langues" : "cel",
    "chames, langues" : "cmc",
    "chamorro" : "cha",
    "chan" : "shn",
    "cherokee" : "chr",
    "chewa" : "nya",
    "cheyenne" : "chy",
    "chibcha" : "chb",
    "chichewa" : "nya",
    "chinois" : "chi",
    "chinook, jargon" : "chn",
    "chipewyan" : "chp",
    "choctaw" : "cho",
    "chuang" : "zha",
    "chuuk" : "chk",
    "copte" : "cop",
    "cornique" : "cor",
    "corse" : "cos",
    "coréen" : "kor",
    "couchitiques, autres langues" : "cus",
    "cree" : "cre",
    "croate" : "scr",
    "créole haïtien" : "hat",
    "créoles et pidgins anglais, autres" : "cpe",
    "créoles et pidgins divers" : "crp",
    "créoles et pidgins français, autres" : "cpf",
    "créoles et pidgins portugais, autres" : "cpp",
    "dakota" : "dak",
    "danois" : "dan",
    "dargwa" : "dar",
    "dayak, langues" : "day",
    "delaware" : "del",
    "dimili" : "zza",
    "dimli" : "zza",
    "dinka" : "din",
    "dioula" : "dyu",
    "diverses, langues" : "mis",
    "djaghataï" : "chg",
    "dogri" : "doi",
    "dogrib" : "dgr",
    "douala" : "dua",
    "dravidiennes, autres langues" : "dra",
    "dzongkha" : "dzo",
    "edo" : "bin",
    "efik" : "efi",
    "ekajuk" : "eka",
    "erza" : "myv",
    "esclave (athapascan)" : "den",
    "espagnol" : "spa",
    "espéranto" : "epo",
    "estonien" : "est",
    "écossais" : "sco",
    "égyptien" : "egy",
    "élamite" : "elx",
    "éwondo" : "ewo",
    "éwé" : "ewe",
    "fang" : "fan",
    "fanti" : "fat",
    "fidjien" : "fij",
    "filipino" : "fil",
    "finno-ougriennes, autres langues" : "fiu",
    "finnois" : "fin",
    "flamand" : "dut",
    "fon" : "fon",
    "français" : "fre",
    "français ancien (842-ca.1400)" : "fro",
    "français moyen (1400-1600)" : "frm",
    "frioulan" : "fur",
    "frison occidental" : "fry",
    "frison oriental" : "frs",
    "frison septentrional" : "frr",
    "féroïen" : "fao",
    "ga" : "gaa",
    "galibi" : "car",
    "galicien" : "glg",
    "galla" : "orm",
    "gallois" : "wel",
    "ganda" : "lug",
    "gayo" : "gay",
    "gaélique" : "gla",
    "gaélique écossais" : "gla",
    "gbaya" : "gba",
    "germaniques, autres langues" : "gem",
    "gond" : "gon",
    "gorontalo" : "gor",
    "gothique" : "got",
    "goudjrati" : "guj",
    "grebo" : "grb",
    "grec ancien (jusqu'à 1453)" : "grc",
    "grec moderne (après 1453)" : "gre",
    "groenlandais" : "kal",
    "guarani" : "grn",
    "guèze" : "gez",
    "gwich´in" : "gwi",
    "géorgien" : "geo",
    "haida" : "hai",
    "haoussa" : "hau",
    "haut-sorabe" : "hsb",
    "hawaïen" : "haw",
    "haïtien" : "hat",
    "herero" : "her",
    "hiligaynon" : "hil",
    "himachali" : "him",
    "hindi" : "hin",
    "hiri motu" : "hmo",
    "hittite" : "hit",
    "hmong" : "hmn",
    "hongrois" : "hun",
    "hupa" : "hup",
    "hébreu" : "heb",
    "iakoute" : "sah",
    "iban" : "iba",
    "ido" : "ido",
    "igbo" : "ibo",
    "ijo, langues" : "ijo",
    "ilocano" : "ilo",
    "indiennes d'amérique centrale, autres langues" : "cai",
    "indiennes d'amérique du nord, autres langues" : "nai",
    "indiennes d'amérique du sud, autres langues" : "sai",
    "indo-aryennes, autres langues" : "inc",
    "indo-européennes, autres langues" : "ine",
    "indonésien" : "ind",
    "indéterminée" : "und",
    "ingouche" : "inh",
    "interlingua (langue auxiliaire internationale)" : "ina",
    "interlingue" : "ile",
    "inuktitut" : "iku",
    "inupiaq" : "ipk",
    "iraniennes, autres langues" : "ira",
    "irlandais" : "gle",
    "irlandais ancien (jusqu'à 900)" : "sga",
    "irlandais moyen (900-1200)" : "mga",
    "iroquoises, langues (famille)" : "iro",
    "islandais" : "ice",
    "italien" : "ita",
    "japonais" : "jpn",
    "javanais" : "jav",
    "jingpho" : "kac",
    "judéo-arabe" : "jrb",
    "judéo-espagnol" : "lad",
    "judéo-persan" : "jpr",
    "kabardien" : "kbd",
    "kabyle" : "kab",
    "kachin" : "kac",
    "kachoube" : "csb",
    "kalmouk" : "xal",
    "kamba" : "kam",
    "kannada" : "kan",
    "kanouri" : "kau",
    "karakalpak" : "kaa",
    "karatchai balkar" : "krc",
    "karen, langues" : "kar",
    "karib" : "car",
    "kashmiri" : "kas",
    "kawi" : "kaw",
    "kazakh" : "kaz",
    "khasi" : "kha",
    "khmer central" : "khm",
    "khoisan, autres langues" : "khi",
    "khotanais" : "kho",
    "kikuyu" : "kik",
    "kimbundu" : "kmb",
    "kirdki" : "zza",
    "kirghiz" : "kir",
    "kiribati" : "gil",
    "kirmanjki" : "zza",
    "klingon" : "tlh",
    "kom" : "kom",
    "kongo" : "kon",
    "konkani" : "kok",
    "kosrae" : "kos",
    "koumyk" : "kum",
    "kpellé" : "kpe",
    "krou, langues" : "kro",
    "kuanyama" : "kua",
    "kurde" : "kur",
    "kurukh" : "kru",
    "kutenai" : "kut",
    "kwanyama" : "kua",
    "lahnda" : "lah",
    "lamba" : "lam",
    "langues des signes" : "sgn",
    "lao" : "lao",
    "latin" : "lat",
    "letton" : "lav",
    "lezghien" : "lez",
    "limbourgeois" : "lim",
    "lingala" : "lin",
    "lituanien" : "lit",
    "lojban" : "jbo",
    "lozi" : "loz",
    "luba-katanga" : "lub",
    "luba-lulua" : "lua",
    "luiseno" : "lui",
    "lunda" : "lun",
    "luo (kenya et tanzanie)" : "luo",
    "lushai" : "lus",
    "luxembourgeois" : "ltz",
    "macédo-roumain" : "rup",
    "macédonien" : "mac",
    "madourais" : "mad",
    "magahi" : "mag",
    "maithili" : "mai",
    "makassar" : "mak",
    "malais" : "may",
    "malayalam" : "mal",
    "malayo-polynésiennes, autres langues" : "map",
    "maldivien" : "div",
    "malgache" : "mlg",
    "maltais" : "mlt",
    "mandar" : "mdr",
    "mandchou" : "mnc",
    "mandingue" : "man",
    "manipuri" : "mni",
    "mannois" : "glv",
    "manobo, langues" : "mno",
    "manx" : "glv",
    "maori" : "mao",
    "maori des îles cook" : "rar",
    "mapuce" : "arn",
    "mapuche" : "arn",
    "mapudungun" : "arn",
    "marathe" : "mar",
    "mari" : "chm",
    "marshall" : "mah",
    "marvari" : "mwr",
    "massaï" : "mas",
    "maya, langues" : "myn",
    "mendé" : "men",
    "mi'kmaq" : "mic",
    "micmac" : "mic",
    "minangkabau" : "min",
    "mirandais" : "mwl",
    "mohawk" : "moh",
    "moksa" : "mdf",
    "moldave" : "mol",
    "mongo" : "lol",
    "mongol" : "mon",
    "moré" : "mos",
    "mounda, langues" : "mun",
    "multilingue" : "mul",
    "muskogee" : "mus",
    "môn-khmer, autres langues" : "mkh",
    "n'ko" : "nqo",
    "nahuatl, langues" : "nah",
    "napolitain" : "nap",
    "nauruan" : "nau",
    "navaho" : "nav",
    "ndonga" : "ndo",
    "ndébélé du nord" : "nde",
    "ndébélé du sud" : "nbl",
    "nepal bhasa" : "new",
    "newari" : "new",
    "newari classique" : "nwc",
    "nias" : "nia",
    "nigéro-congolaises, autres langues" : "nic",
    "nilo-sahariennes, autres langues" : "ssa",
    "niué" : "niu",
    "nogay" : "nog",
    "nogaï" : "nog",
    "norrois, vieux" : "non",
    "norvégien" : "nor",
    "norvégien bokmål" : "nob",
    "norvégien nynorsk" : "nno",
    "nubiennes, langues" : "nub",
    "nyamwezi" : "nym",
    "nyanja" : "nya",
    "nyankolé" : "nyn",
    "nyoro" : "nyo",
    "nzema" : "nzi",
    "néerlandais" : "dut",
    "néerlandais moyen (ca. 1050-1350)" : "dum",
    "népalais" : "nep",
    "occitan (après 1500)" : "oci",
    "ojibwa" : "oji",
    "oriya" : "ori",
    "osage" : "osa",
    "ossète" : "oss",
    "otomangue, langues" : "oto",
    "oudmourte" : "udm",
    "ougaritique" : "uga",
    "ourdou" : "urd",
    "ouszbek" : "uzb",
    "ouïgour" : "uig",
    "oïrat" : "xal",
    "pachto" : "pus",
    "pahlavi" : "pal",
    "palau" : "pau",
    "pali" : "pli",
    "pampangan" : "pam",
    "pangasinan" : "pag",
    "papiamento" : "pap",
    "papoues, autres langues" : "paa",
    "pas de contenu linguistique" : "zxx",
    "pedi" : "nso",
    "pendjabi" : "pan",
    "persan" : "per",
    "perse, vieux (ca. 600-400 av. j.-c.)" : "peo",
    "peul" : "ful",
    "philippines, autres langues" : "phi",
    "phénicien" : "phn",
    "pilipino" : "fil",
    "pohnpei" : "pon",
    "polonais" : "pol",
    "portugais" : "por",
    "provençal" : "oci",
    "provençal ancien (jusqu'à 1500)" : "pro",
    "prâkrit" : "pra",
    "quechua" : "que",
    "rajasthani" : "raj",
    "rapanui" : "rap",
    "rarotonga" : "rar",
    "romanche" : "roh",
    "romanes, autres langues" : "roa",
    "romanian" : "ron",
    "roumain" : "rum",
    "rundi" : "run",
    "russe" : "rus",
    "rwanda" : "kin",
    "réservée à l'usage local" : "qaa-qtz",
    "salish, langues" : "sal",
    "samaritain" : "sam",
    "sami d'inari" : "smn",
    "sami de lule" : "smj",
    "sami du nord" : "sme",
    "sami du sud" : "sma",
    "sami skolt" : "sms",
    "sami, autres langues" : "smi",
    "samoan" : "smo",
    "sandawe" : "sad",
    "sango" : "sag",
    "sanskrit" : "san",
    "santal" : "sat",
    "sarde" : "srd",
    "sasak" : "sas",
    "saxon, bas" : "nds",
    "selkoupe" : "sel",
    "sepedi" : "nso",
    "serbe" : "scc",
    "shona" : "sna",
    "sicilien" : "scn",
    "sidamo" : "sid",
    "sindhi" : "snd",
    "singhalais" : "sin",
    "sino-tibétaines, autres langues" : "sit",
    "sioux, langues" : "sio",
    "slaves, autres langues" : "sla",
    "slavon d'église" : "chu",
    "slavon liturgique" : "chu",
    "slovaque" : "slo",
    "slovène" : "slv",
    "sogdien" : "sog",
    "somali" : "som",
    "songhai, langues" : "son",
    "soninké" : "snk",
    "sorabes, langues" : "wen",
    "sotho du nord" : "nso",
    "sotho du sud" : "sot",
    "soundanais" : "sun",
    "soussou" : "sus",
    "sranan tongo" : "srn",
    "sukuma" : "suk",
    "sumérien" : "sux",
    "suédois" : "swe",
    "swahili" : "swa",
    "swati" : "ssw",
    "syriaque" : "syr",
    "sémitiques, autres langues" : "sem",
    "sérère" : "srr",
    "tadjik" : "tgk",
    "tagalog" : "tgl",
    "tahitien" : "tah",
    "tamacheq" : "tmh",
    "tamoul" : "tam",
    "tatar" : "tat",
    "tatar de crimé" : "crh",
    "tchouvache" : "chv",
    "tchèque" : "cze",
    "tchétchène" : "che",
    "temne" : "tem",
    "tereno" : "ter",
    "tetum" : "tet",
    "thaï" : "tha",
    "thaïes, autres langues" : "tai",
    "tibétain" : "tib",
    "tigrigna" : "tir",
    "tigré" : "tig",
    "tiv" : "tiv",
    "tlingit" : "tli",
    "tok pisin" : "tpi",
    "tokelau" : "tkl",
    "tonga (nyasa)" : "tog",
    "tongan (îles tonga)" : "ton",
    "touva" : "tyv",
    "tsigane" : "rom",
    "tsimshian" : "tsi",
    "tsonga" : "tso",
    "tswana" : "tsn",
    "tumbuka" : "tum",
    "tupi, langues" : "tup",
    "turc" : "tur",
    "turc ottoman (1500-1928)" : "ota",
    "turkmène" : "tuk",
    "tuvalu" : "tvl",
    "twi" : "twi",
    "télougou" : "tel",
    "ukrainien" : "ukr",
    "umbundu" : "umb",
    "valencien" : "cat",
    "vaï" : "vai",
    "venda" : "ven",
    "vietnamien" : "vie",
    "vieux bulgare" : "chu",
    "vieux slave" : "chu",
    "volapük" : "vol",
    "vote" : "vot",
    "wakashennes, langues" : "wak",
    "walamo" : "wal",
    "wallon" : "wln",
    "waray" : "war",
    "washo" : "was",
    "wolof" : "wol",
    "xhosa" : "xho",
    "yao" : "yao",
    "yapois" : "yap",
    "yi de sichuan" : "iii",
    "yiddish" : "yid",
    "yoruba" : "yor",
    "yupik, langues" : "ypk",
    "zandé, langues" : "znd",
    "zapotèque" : "zap",
    "zaza" : "zza",
    "zazaki" : "zza",
    "zenaga" : "zen",
    "zhuang" : "zha",
    "zoulou" : "zul",
    "zuni" : "zun"
}

english_to_iso639_2 = {
    "afar" : "aar",
    "abkhazian" : "abk",
    "achinese" : "ace",
    "acoli" : "ach",
    "adangme" : "ada",
    "adyghe" : "ady",
    "adygei" : "ady",
    "afro-asiatic (other)" : "afa",
    "afrihili" : "afh",
    "afrikaans" : "afr",
    "ainu" : "ain",
    "akan" : "aka",
    "akkadian" : "akk",
    "albanian" : "alb",
    "aleut" : "ale",
    "algonquian languages" : "alg",
    "southern altai" : "alt",
    "amharic" : "amh",
    "english, old (ca.450-1100)" : "ang",
    "angika" : "anp",
    "apache languages" : "apa",
    "arabic" : "ara",
    "aramaic" : "arc",
    "aragonese" : "arg",
    "armenian" : "arm",
    "mapudungun" : "arn",
    "mapuche" : "arn",
    "arapaho" : "arp",
    "artificial (other)" : "art",
    "arawak" : "arw",
    "assamese" : "asm",
    "asturian" : "ast",
    "bable" : "ast",
    "athapascan languages" : "ath",
    "australian languages" : "aus",
    "avaric" : "ava",
    "avestan" : "ave",
    "awadhi" : "awa",
    "aymara" : "aym",
    "azerbaijani" : "aze",
    "banda languages" : "bad",
    "bamileke languages" : "bai",
    "bashkir" : "bak",
    "baluchi" : "bal",
    "bambara" : "bam",
    "balinese" : "ban",
    "basque" : "baq",
    "basa" : "bas",
    "baltic (other)" : "bat",
    "beja" : "bej",
    "belarusian" : "bel",
    "bemba" : "bem",
    "bengali" : "ben",
    "berber (other)" : "ber",
    "bhojpuri" : "bho",
    "bihari" : "bih",
    "bikol" : "bik",
    "bini" : "bin",
    "edo" : "bin",
    "bislama" : "bis",
    "siksika" : "bla",
    "bantu (other)" : "bnt",
    "bosnian" : "bos",
    "braj" : "bra",
    "breton" : "bre",
    "batak languages" : "btk",
    "buriat" : "bua",
    "buginese" : "bug",
    "bulgarian" : "bul",
    "burmese" : "bur",
    "bilin" : "byn",
    "blin" : "byn",
    "caddo" : "cad",
    "central american indian (other)" : "cai",
    "galibi carib" : "car",
    "catalan" : "cat",
    "valencian" : "cat",
    "caucasian (other)" : "cau",
    "cebuano" : "ceb",
    "celtic (other)" : "cel",
    "chamorro" : "cha",
    "chibcha" : "chb",
    "chechen" : "che",
    "chagatai" : "chg",
    "chinese" : "chi",
    "chuukese" : "chk",
    "mari" : "chm",
    "chinook jargon" : "chn",
    "choctaw" : "cho",
    "chipewyan" : "chp",
    "cherokee" : "chr",
    "church slavic" : "chu",
    "old slavonic" : "chu",
    "church slavonic" : "chu",
    "old bulgarian" : "chu",
    "old church slavonic" : "chu",
    "chuvash" : "chv",
    "cheyenne" : "chy",
    "chamic languages" : "cmc",
    "coptic" : "cop",
    "cornish" : "cor",
    "corsican" : "cos",
    "creoles and pidgins, english based (other)" : "cpe",
    "creoles and pidgins, french-based (other)" : "cpf",
    "creoles and pidgins, portuguese-based (other)" : "cpp",
    "cree" : "cre",
    "crimean turkish" : "crh",
    "crimean tatar" : "crh",
    "creoles and pidgins (other)" : "crp",
    "kashubian" : "csb",
    "cushitic (other)" : "cus",
    "czech" : "cze",
    "dakota" : "dak",
    "danish" : "dan",
    "dargwa" : "dar",
    "land dayak languages" : "day",
    "delaware" : "del",
    "slave (athapascan)" : "den",
    "dogrib" : "dgr",
    "dinka" : "din",
    "divehi" : "div",
    "dhivehi" : "div",
    "maldivian" : "div",
    "dogri" : "doi",
    "dravidian (other)" : "dra",
    "lower sorbian" : "dsb",
    "duala" : "dua",
    "dutch, middle (ca.1050-1350)" : "dum",
    "dutch" : "dut",
    "flemish" : "dut",
    "dyula" : "dyu",
    "dzongkha" : "dzo",
    "efik" : "efi",
    "egyptian (ancient)" : "egy",
    "ekajuk" : "eka",
    "elamite" : "elx",
    "english" : "eng",
    "english, middle (1100-1500)" : "enm",
    "esperanto" : "epo",
    "estonian" : "est",
    "ewe" : "ewe",
    "ewondo" : "ewo",
    "fang" : "fan",
    "faroese" : "fao",
    "fanti" : "fat",
    "fijian" : "fij",
    "filipino" : "fil",
    "pilipino" : "fil",
    "finnish" : "fin",
    "finno-ugrian (other)" : "fiu",
    "fon" : "fon",
    "french" : "fre",
    "french, middle (ca.1400-1600)" : "frm",
    "french, old (842-ca.1400)" : "fro",
    "northern frisian" : "frr",
    "eastern frisian" : "frs",
    "western frisian" : "fry",
    "fulah" : "ful",
    "friulian" : "fur",
    "ga" : "gaa",
    "gayo" : "gay",
    "gbaya" : "gba",
    "germanic (other)" : "gem",
    "georgian" : "geo",
    "german" : "ger",
    "geez" : "gez",
    "gilbertese" : "gil",
    "gaelic" : "gla",
    "scottish gaelic" : "gla",
    "irish" : "gle",
    "galician" : "glg",
    "manx" : "glv",
    "german, middle high (ca.1050-1500)" : "gmh",
    "german, old high (ca.750-1050)" : "goh",
    "gondi" : "gon",
    "gorontalo" : "gor",
    "gothic" : "got",
    "grebo" : "grb",
    "greek, ancient (to 1453)" : "grc",
    "greek, modern (1453-)" : "gre",
    "guarani" : "grn",
    "alemannic" : "gsw",
    "swiss german" : "gsw",
    "gujarati" : "guj",
    "gwich´in" : "gwi",
    "haida" : "hai",
    "haitian" : "hat",
    "haitian creole" : "hat",
    "hausa" : "hau",
    "hawaiian" : "haw",
    "hebrew" : "heb",
    "herero" : "her",
    "hiligaynon" : "hil",
    "himachali" : "him",
    "hindi" : "hin",
    "hittite" : "hit",
    "hmong" : "hmn",
    "hiri motu" : "hmo",
    "upper sorbian" : "hsb",
    "hungarian" : "hun",
    "hupa" : "hup",
    "iban" : "iba",
    "igbo" : "ibo",
    "icelandic" : "ice",
    "ido" : "ido",
    "sichuan yi" : "iii",
    "ijo languages" : "ijo",
    "inuktitut" : "iku",
    "interlingue" : "ile",
    "iloko" : "ilo",
    "interlingua (international auxiliary language association)" : "ina",
    "indic (other)" : "inc",
    "indonesian" : "ind",
    "indo-european (other)" : "ine",
    "ingush" : "inh",
    "inupiaq" : "ipk",
    "iranian (other)" : "ira",
    "iroquoian languages" : "iro",
    "italian" : "ita",
    "javanese" : "jav",
    "lojban" : "jbo",
    "japanese" : "jpn",
    "judeo-persian" : "jpr",
    "judeo-arabic" : "jrb",
    "kara-kalpak" : "kaa",
    "kabyle" : "kab",
    "kachin" : "kac",
    "jingpho" : "kac",
    "kalaallisut" : "kal",
    "greenlandic" : "kal",
    "kamba" : "kam",
    "kannada" : "kan",
    "karen languages" : "kar",
    "kashmiri" : "kas",
    "kanuri" : "kau",
    "kawi" : "kaw",
    "kazakh" : "kaz",
    "kabardian" : "kbd",
    "khasi" : "kha",
    "khoisan (other)" : "khi",
    "central khmer" : "khm",
    "khotanese" : "kho",
    "kikuyu" : "kik",
    "gikuyu" : "kik",
    "kinyarwanda" : "kin",
    "kyrgyz" : "kir",
    "kirghiz" : "kir",
    "kimbundu" : "kmb",
    "konkani" : "kok",
    "komi" : "kom",
    "kongo" : "kon",
    "korean" : "kor",
    "kosraean" : "kos",
    "kpelle" : "kpe",
    "karachay-balkar" : "krc",
    "kru languages" : "kro",
    "kurukh" : "kru",
    "kuanyama" : "kua",
    "kwanyama" : "kua",
    "kumyk" : "kum",
    "kurdish" : "kur",
    "kutenai" : "kut",
    "ladino" : "lad",
    "lahnda" : "lah",
    "lamba" : "lam",
    "lao" : "lao",
    "latin" : "lat",
    "latvian" : "lav",
    "lezghian" : "lez",
    "limburgan" : "lim",
    "limburger" : "lim",
    "limburgish" : "lim",
    "lingala" : "lin",
    "lithuanian" : "lit",
    "mongo" : "lol",
    "lozi" : "loz",
    "luxembourgish" : "ltz",
    "letzeburgesch" : "ltz",
    "luba-lulua" : "lua",
    "luba-katanga" : "lub",
    "ganda" : "lug",
    "luiseno" : "lui",
    "lunda" : "lun",
    "luo (kenya and tanzania)" : "luo",
    "lushai" : "lus",
    "macedonian" : "mac",
    "madurese" : "mad",
    "magahi" : "mag",
    "marshallese" : "mah",
    "maithili" : "mai",
    "makasar" : "mak",
    "malayalam" : "mal",
    "mandingo" : "man",
    "maori" : "mao",
    "austronesian (other)" : "map",
    "marathi" : "mar",
    "masai" : "mas",
    "malay" : "may",
    "moksha" : "mdf",
    "mandar" : "mdr",
    "mende" : "men",
    "irish, middle (900-1200)" : "mga",
    "mi'kmaq" : "mic",
    "micmac" : "mic",
    "minangkabau" : "min",
    "miscellaneous languages" : "mis",
    "mon-khmer (other)" : "mkh",
    "malagasy" : "mlg",
    "maltese" : "mlt",
    "manchu" : "mnc",
    "manipuri" : "mni",
    "manobo languages" : "mno",
    "mohawk" : "moh",
    "moldavian" : "mol",
    "mongolian" : "mon",
    "mossi" : "mos",
    "multiple languages" : "mul",
    "munda languages" : "mun",
    "creek" : "mus",
    "mirandese" : "mwl",
    "marwari" : "mwr",
    "mayan languages" : "myn",
    "erzya" : "myv",
    "nahuatl languages" : "nah",
    "north american indian" : "nai",
    "neapolitan" : "nap",
    "nauru" : "nau",
    "navajo" : "nav",
    "navaho" : "nav",
    "ndebele, south" : "nbl",
    "south ndebele" : "nbl",
    "ndebele, north" : "nde",
    "north ndebele" : "nde",
    "ndonga" : "ndo",
    "german, low" : "nds",
    "low german" : "nds",
    "saxon, low" : "nds",
    "low saxon" : "nds",
    "nepali" : "nep",
    "newari" : "new",
    "nepal bhasa" : "new",
    "nias" : "nia",
    "niger-kordofanian (other)" : "nic",
    "niuean" : "niu",
    "norwegian nynorsk" : "nno",
    "nynorsk, norwegian" : "nno",
    "bokmål, norwegian" : "nob",
    "norwegian bokmål" : "nob",
    "nogai" : "nog",
    "norse, old" : "non",
    "norwegian" : "nor",
    "n'ko" : "nqo",
    "pedi" : "nso",
    "sepedi" : "nso",
    "northern sotho" : "nso",
    "nubian languages" : "nub",
    "classical newari" : "nwc",
    "old newari" : "nwc",
    "classical nepal bhasa" : "nwc",
    "chichewa" : "nya",
    "chewa" : "nya",
    "nyanja" : "nya",
    "nyamwezi" : "nym",
    "nyankole" : "nyn",
    "nyoro" : "nyo",
    "nzima" : "nzi",
    "occitan (post 1500)" : "oci",
    "provençal" : "oci",
    "ojibwa" : "oji",
    "oriya" : "ori",
    "oromo" : "orm",
    "osage" : "osa",
    "ossetian" : "oss",
    "ossetic" : "oss",
    "turkish, ottoman (1500-1928)" : "ota",
    "otomian languages" : "oto",
    "papuan (other)" : "paa",
    "pangasinan" : "pag",
    "pahlavi" : "pal",
    "pampanga" : "pam",
    "punjabi" : "pan",
    "panjabi" : "pan",
    "papiamento" : "pap",
    "palauan" : "pau",
    "persian, old (ca.600-400 b.c.)" : "peo",
    "persian" : "per",
    "philippine (other)" : "phi",
    "phoenician" : "phn",
    "pali" : "pli",
    "polish" : "pol",
    "pohnpeian" : "pon",
    "portuguese" : "por",
    "prakrit languages" : "pra",
    "provençal, old (to 1500)" : "pro",
    "pushto" : "pus",
    "reserved for local use" : "qaa-qtz",
    "quechua" : "que",
    "rajasthani" : "raj",
    "rapanui" : "rap",
    "rarotongan" : "rar",
    "cook islands maori" : "rar",
    "romance (other)" : "roa",
    "romansh" : "roh",
    "romany" : "rom",
    "romanian" : "rum",
    "rundi" : "run",
    "aromanian" : "rup",
    "arumanian" : "rup",
    "macedo-romanian" : "rup",
    "russian" : "rus",
    "sandawe" : "sad",
    "sango" : "sag",
    "yakut" : "sah",
    "south american indian (other)" : "sai",
    "salishan languages" : "sal",
    "samaritan aramaic" : "sam",
    "sanskrit" : "san",
    "sasak" : "sas",
    "santali" : "sat",
    "serbian" : "scc",
    "sicilian" : "scn",
    "scots" : "sco",
    "croatian" : "scr",
    "selkup" : "sel",
    "semitic (other)" : "sem",
    "irish, old (to 900)" : "sga",
    "sign languages" : "sgn",
    "shan" : "shn",
    "sidamo" : "sid",
    "sinhala" : "sin",
    "sinhalese" : "sin",
    "siouan languages" : "sio",
    "sino-tibetan (other)" : "sit",
    "slavic (other)" : "sla",
    "slovak" : "slo",
    "slovenian" : "slv",
    "southern sami" : "sma",
    "northern sami" : "sme",
    "sami languages (other)" : "smi",
    "lule sami" : "smj",
    "inari sami" : "smn",
    "samoan" : "smo",
    "skolt sami" : "sms",
    "shona" : "sna",
    "sindhi" : "snd",
    "soninke" : "snk",
    "sogdian" : "sog",
    "somali" : "som",
    "songhai languages" : "son",
    "sotho, southern" : "sot",
    "spanish" : "spa",
    "castilian" : "spa",
    "sardinian" : "srd",
    "sranan tongo" : "srn",
    "serer" : "srr",
    "nilo-saharan (other)" : "ssa",
    "swati" : "ssw",
    "sukuma" : "suk",
    "sundanese" : "sun",
    "susu" : "sus",
    "sumerian" : "sux",
    "swahili" : "swa",
    "swedish" : "swe",
    "syriac" : "syr",
    "tahitian" : "tah",
    "tai (other)" : "tai",
    "tamil" : "tam",
    "tatar" : "tat",
    "telugu" : "tel",
    "timne" : "tem",
    "tereno" : "ter",
    "tetum" : "tet",
    "tajik" : "tgk",
    "tagalog" : "tgl",
    "thai" : "tha",
    "tibetan" : "tib",
    "tigre" : "tig",
    "tigrinya" : "tir",
    "tiv" : "tiv",
    "tokelau" : "tkl",
    "klingon" : "tlh",
    "tlhingan-hol" : "tlh",
    "tlingit" : "tli",
    "tamashek" : "tmh",
    "tonga (nyasa)" : "tog",
    "tonga (tonga islands)" : "ton",
    "tok pisin" : "tpi",
    "tsimshian" : "tsi",
    "tswana" : "tsn",
    "tsonga" : "tso",
    "turkmen" : "tuk",
    "tumbuka" : "tum",
    "tupi languages" : "tup",
    "turkish" : "tur",
    "altaic (other)" : "tut",
    "tuvalu" : "tvl",
    "twi" : "twi",
    "tuvinian" : "tyv",
    "udmurt" : "udm",
    "ugaritic" : "uga",
    "uighur" : "uig",
    "uyghur" : "uig",
    "ukrainian" : "ukr",
    "umbundu" : "umb",
    "undetermined" : "und",
    "urdu" : "urd",
    "uzbek" : "uzb",
    "vai" : "vai",
    "venda" : "ven",
    "vietnamese" : "vie",
    "volapük" : "vol",
    "votic" : "vot",
    "wakashan languages" : "wak",
    "walamo" : "wal",
    "waray" : "war",
    "washo" : "was",
    "welsh" : "wel",
    "sorbian languages" : "wen",
    "walloon" : "wln",
    "wolof" : "wol",
    "kalmyk" : "xal",
    "oirat" : "xal",
    "xhosa" : "xho",
    "yao" : "yao",
    "yapese" : "yap",
    "yiddish" : "yid",
    "yoruba" : "yor",
    "yupik languages" : "ypk",
    "zapotec" : "zap",
    "zenaga" : "zen",
    "chuang" : "zha",
    "zhuang" : "zha",
    "zande languages" : "znd",
    "zulu" : "zul",
    "zuni" : "zun",
    "no linguistic content" : "zxx",
    "zaza" : "zza",
    "dimili" : "zza",
    "dimli" : "zza",
    "kirdki" : "zza",
    "kirmanjki" : "zza",
    "zazaki" : "zza"
}

def find_language_authority(language) :
    if language :
        language = language.lower()
        minus_index = language.find("-")
        if len(language) == 2 and language in iso639_1_to_iso639_2 :
            return "iso639-1"
        elif minus_index == 2 and language[:2] in iso639_1_to_iso639_2 :
            return "rfc5646"
        elif len(language) == 3 and language in iso639_2_to_iso639_1 :
            return "iso639-2b"
        elif minus_index == 3 and language[:3] in iso639_2_to_iso639_1 :
            return "rfc5646"
        else :
            print "Fixme ! Unknown language authority for language code : {}".format(language)
    return None

def convert_iso639_1_to_iso639_2(iso639_1) :
    if iso639_1 :
        iso639_1 = iso639_1.lower()
        if iso639_1 in iso639_1_to_iso639_2 :
            return iso639_1_to_iso639_2[iso639_1]

def convert_iso639_2_to_iso639_1(iso639_2) :
    if iso639_2 :
        iso639_2 = iso639_2.lower()
        if iso639_2 in iso639_2_to_iso639_1 :
            return iso639_2_to_iso639_1[iso639_2]
        else : 
            return iso639_2

def convert_iso639_1_to_rfc5646(iso639_1) :
    if iso639_1 :
        return iso639_1.lower()

def convert_iso639_2_to_rfc5646(iso639_2) :
    return convert_iso639_2_to_iso639_1(iso639_2)

def convert_rfc5646_to_iso639_2(rfc5646) :
    # RFC5646 langtag =
    #                   language
    #                   ["-" script]
    #                   ["-" region]
    #                   *("-" variant)
    #                   *("-" extension)
    #                   ["-" privateuse]
    # 
    # Example:
    # - "fr" (French)
    # - "de-AT" (German as used in Austria)
    # - "zh-Hant" (Chinese written using the Traditional Chinese script)
    # - "zh-Hans" (Chinese written using the Simplified Chinese script)
    # - "zh-yue-HK" (Chinese, Cantonese, as used in Hong Kong SAR)
    # - "sr-Latn-RS" (Serbian written using Latin script as used in Serbia ('RS').
    # - "es-419" (Spanish appropriate to the UN-defined Latin America and Caribbean region ('419'))
    # - "en-scotland-fonipa" (English, Scottish dialect, IPA phonetic transcription)
    # - "sl-rozaj-biske" (San Giorgio dialect of Resian dialect of Slovenian)
    # - "hy-Latn-IT-arevela" (Eastern Armenian written in Latin script, as used in Italy)
    # 
    # 
    #  language      = 2*3ALPHA            ; shortest ISO 639 code
    #                  ["-" extlang]       ; sometimes followed by
    #                                      ; extended language subtags
    #                / 4ALPHA              ; or reserved for future use
    #                / 5*8ALPHA            ; or registered language subtag
    # 
    #  extlang       = 3ALPHA              ; selected ISO 639 codes
    #                  *2("-" 3ALPHA)      ; permanently reserved
    # 
    #  script        = 4ALPHA              ; ISO 15924 code
    # 
    #  region        = 2ALPHA              ; ISO 3166-1 code
    #                / 3DIGIT              ; UN M.49 code
    # 
    #  variant       = 5*8alphanum         ; registered variants
    #                / (DIGIT 3alphanum)
    # 
    #  extension     = singleton 1*("-" (2*8alphanum))
    # 
    #                                      ; Single alphanumerics
    #                                      ; "x" reserved for private use
    #  singleton     = DIGIT               ; 0 - 9
    #                / %x41-57             ; A - W
    #                / %x59-5A             ; Y - Z
    #                / %x61-77             ; a - w
    #                / %x79-7A             ; y - z
    # 
    #  privateuse    = "x" 1*("-" (1*8alphanum))
    # 
    #  grandfathered = irregular           ; non-redundant tags registered
    #                / regular             ; during the RFC 5646 era
    # 
    #  irregular     = "en-GB-oed"         ; irregular tags do not match
    #                / "i-ami"             ; the 'langtag' production and
    #                / "i-bnn"             ; would not otherwise be
    #                / "i-default"         ; considered 'well-formed'
    #                / "i-enochian"        ; These tags are all valid,
    #                / "i-hak"             ; but most are deprecated
    #                / "i-klingon"         ; in favor of more modern
    #                / "i-lux"             ; subtags or subtag
    #                / "i-mingo"           ; combination
    #                / "i-navajo"
    #                / "i-pwn"
    #                / "i-tao"
    #                / "i-tay"
    #                / "i-tsu"
    #                / "sgn-BE-FR"
    #                / "sgn-BE-NL"
    #                / "sgn-CH-DE"
    # 
    #  regular       = "art-lojban"        ; these tags match the 'langtag'
    #                / "cel-gaulish"       ; production, but their subtags
    #                / "no-bok"            ; are not extended language
    #                / "no-nyn"            ; or variant subtags: their meaning
    #                / "zh-guoyu"          ; is defined by their registration
    #                / "zh-hakka"          ; and all of these are deprecated
    #                / "zh-min"            ; in favor of a more modern
    #                / "zh-min-nan"        ; subtag or sequence of subtags
    #                / "zh-xiang"
    # 
    #  alphanum      = (ALPHA / DIGIT)     ; letters and numbers
    # 
    # Simplified RFC5646 formats managed by this function :
    # "i-" <iana_registered_code>
    # "x-" <private_use_code>
    # <iso_639_1_code>
    # <iso_639_2_code>
    # <iso_639_1or2_code> "-" <iso_3166_code>
    # <iso_639_1or2_code> "-" <iso_15924_code>
    # <iso_639_1or2_code> "-" <iso_15924_code> "-" <iso_3166_code>

    if rfc5646 :
        rfc5646 = rfc5646.lower();
        first_minus_index = rfc5646.find("-")

        if first_minus_index == 3 or len(rfc5646) == 3 :
            # iso_639_2 ?
            if rfc5646[:3] in iso639_2_to_iso639_1 :
                return rfc5646[:3]
            else :
                print "Fixme ! Unknown language format, not an iso639_2 : {}".format(rfc5646)

        elif first_minus_index == 2 or len(rfc5646) == 2 :
            # iso_639_1 ?
            if rfc5646[:2] in iso639_1_to_iso639_2 :
                return convert_iso639_1_to_iso639_2(rfc5646[:2])
            else :
                print "Fixme ! Unknown language format, not an iso639_1 : {}".format(rfc5646)

        elif first_minus_index == 1 :
            first_char = rfc5646[:1]
            if first_char == "i" :
                # iana_registered_code
                print "Fixme ! iana_registered_code is not managed for rfc5646 : {}".format(rfc5646)
            elif first_char == "x" :
                # private_use_code
                print "Fixme ! private_use_code is not managed for rfc5646 : {}".format(rfc5646)
            else :
                # unknown 
                print "Fixme ! Unknown prefix code for rfc5646 : {}".format(rfc5646)

        else :
            print "Fixme ! Unknown language format for rfc5646 : {}".format(rfc5646)

def convert_rfc5646_to_iso639_1(rfc5646) :
    return convert_iso639_2_to_iso639_1(convert_rfc5646_to_iso639_2(rfc5646))

def convert_french_to_iso639_2(french) :
    if french :
        french=french.lower()
        if french in french_to_iso639_2 :
            return french_to_iso639_2[french]

def convert_english_to_iso639_2(english) :
    if english :
        english=english.lower()
        if english in english_to_iso639_2 :
            return english_to_iso639_2[english]

def convert_english_to_rfc5646(english) :
    iso639_2 = convert_english_to_iso639_2(english)
    return convert_iso639_2_to_rfc5646(iso639_2)

def convert_unknown_format_to_iso639_2(unknown) :
    if unknown :
        result = convert_rfc5646_to_iso639_2(unknown)
        if not result :
            result = convert_french_to_iso639_2(unknown)
        if not result :
            result = convert_english_to_iso639_2(unknown)
        return result

def test() :
    print convert_iso639_2_to_iso639_1("fre")
    print convert_iso639_1_to_iso639_2("fr")
    print convert_french_to_iso639_2("français")
    print convert_english_to_iso639_2("french")
    print convert_rfc5646_to_iso639_1("fr-FR")
    print convert_rfc5646_to_iso639_2("fr-FR")
    print convert_unknown_format_to_iso639_2("fr")

#test()
